/*
 Highcharts JS v2.1.9 (2011-11-11)

 (c) 2009-2011 Torstein H?nsi

 License: www.highcharts.com/license
*/
(function(){function F(a,b){var c;a||(a={});for(c in b)a[c]=b[c];return a}function Ka(){for(var a=0,b=arguments,c=b.length,d={};a<c;a++)d[b[a++]]=b[a];return d}function M(a,b){return parseInt(a,b||10)}function jb(a){return"string"===typeof a}function Aa(a){return"object"===typeof a}function kb(a){return"number"===typeof a}function qb(a){return ka.log(a)/ka.LN10}function qc(a){return ka.pow(10,a)}function rb(a,b){for(var c=a.length;c--;)if(a[c]===b){a.splice(c,1);break}}function r(a){return a!==ha&&
null!==a}function P(a,b,c){var d,e;if(jb(b))r(c)?a.setAttribute(b,c):a&&a.getAttribute&&(e=a.getAttribute(b));else if(r(b)&&Aa(b))for(d in b)a.setAttribute(d,b[d]);return e}function sb(a){return"[object Array]"===Object.prototype.toString.call(a)?a:[a]}function p(){var a=arguments,b,c,d=a.length;for(b=0;b<d;b++)if(c=a[b],"undefined"!==typeof c&&null!==c)return c}function y(a,b){if(Rb&&b&&b.opacity!==ha)b.filter="alpha(opacity="+100*b.opacity+")";F(a.style,b)}function aa(a,b,c,d,e){a=s.createElement(a);
b&&F(a,b);e&&y(a,{padding:0,border:ma,margin:0});c&&y(a,c);d&&d.appendChild(a);return a}function V(a,b){var c=function(){};c.prototype=new a;F(c.prototype,b);return c}function cc(a,b,c,d){var e=Oa.lang,f=isNaN(b=va(b))?2:b,b=void 0===c?e.decimalPoint:c,d=void 0===d?e.thousandsSep:d,e=0>a?"-":"",c=""+M(a=va(+a||0).toFixed(f)),g=3<c.length?c.length%3:0;return e+(g?c.substr(0,g)+d:"")+c.substr(g).replace(/(\d{3})(?=\d)/g,"$1"+d)+(f?b+va(a-c).toFixed(f).slice(2):"")}function rc(a,b,c,d){var e,c=p(c,1);
e=a/c;if(!b&&(b=[1,2,2.5,5,10],d&&(!1===d.allowDecimals||"logarithmic"===d.type)))1===c?b=[1,2,5,10]:0.1>=c&&(b=[1/c]);for(d=0;d<b.length&&!(a=b[d],e<=(b[d]+(b[d+1]||b[d]))/2);d++);return a*c}function sc(){this.symbol=this.color=0}function Jc(a,b,c,d,e,f,g,h){var i=g.x,g=g.y,j=i-a+c-h,k=g-b+d+15,n;7>j&&(j=c+i+h);j+a>c+e&&(j-=j+a-(c+e),k=g-b+d-h,n=!0);k<d+5?(k=d+5,n&&g>=k&&g<=k+b&&(k=g+d+h)):k+b>d+f&&(k=d+f-b-h);return{x:j,y:k}}function Kc(a,b){var c=a.length,d,e;for(e=0;e<c;e++)a[e].ss_i=e;a.sort(function(a,
c){d=b(a,c);return 0===d?a.ss_i-c.ss_i:d});for(e=0;e<c;e++)delete a[e].ss_i}function Gb(a){for(var b=a.length,c=a[0];b--;)a[b]<c&&(c=a[b]);return c}function tb(a){for(var b=a.length,c=a[0];b--;)a[b]>c&&(c=a[b]);return c}function Hb(a){for(var b in a)a[b]&&a[b].destroy&&a[b].destroy(),delete a[b]}function ub(a,b){Ib=p(a,b.animation)}function Jb(){var a=Oa.global.useUTC;Sb=a?Date.UTC:function(a,c,d,e,f,g){return(new Date(a,c,p(d,1),p(e,0),p(f,0),p(g,0))).getTime()};dc=a?"getUTCMinutes":"getMinutes";
ec=a?"getUTCHours":"getHours";fc=a?"getUTCDay":"getDay";Kb=a?"getUTCDate":"getDate";Tb=a?"getUTCMonth":"getMonth";Ub=a?"getUTCFullYear":"getFullYear";tc=a?"setUTCMinutes":"setMinutes";uc=a?"setUTCHours":"setHours";gc=a?"setUTCDate":"setDate";vc=a?"setUTCMonth":"setMonth";wc=a?"setUTCFullYear":"setFullYear"}function vb(a){Za||(Za=aa(bb));a&&Za.appendChild(a);Za.innerHTML=""}function cb(){}function Vb(a,b){function c(a){function b(a,c){this.pos=a;this.type=c||"";this.isNew=!0;c||this.addLabel()}function c(a){if(a)this.options=
a,this.id=a.id;return this}function d(a,b,c,e){this.isNegative=b;this.options=a;this.x=c;this.stack=e;this.alignOptions={align:a.align||(S?b?"left":"right":"center"),verticalAlign:a.verticalAlign||(S?"middle":b?"bottom":"top"),y:p(a.y,S?4:b?14:-6),x:p(a.x,S?b?-6:6:0)};this.textAlign=a.textAlign||(S?b?"right":"left":"center")}function e(){var a=[],b=[],c;E=N=null;o(x.series,function(e){if(e.visible||!t.ignoreHiddenSeries){var f=e.options,g,h,k,i,m,l,n,K,B,x=f.threshold,na,o=[],u=0;if(j)f=e.xData,f.length&&
(E=Ta(p(E,f[0]),Gb(f)),N=W(p(N,f[0]),tb(f)));else{var hc,U,C,A=e.cropped,T=e.xAxis.getExtremes(),z=!!e.modifyValue;g=f.stacking;Ma="percent"===g;if(g)m=f.stack,i=e.type+p(m,""),l="-"+i,e.stackKey=i,h=a[i]||[],a[i]=h,k=b[l]||[],b[l]=k;Ma&&(E=0,N=99);e.processData();f=e.processedXData;n=e.processedYData;na=n.length;for(c=0;c<na;c++)if(K=f[c],B=n[c],null!==B&&B!==ha&&(g?(U=(hc=B<x)?k:h,C=hc?l:i,B=U[K]=r(U[K])?U[K]+B:B,q[C]||(q[C]={}),q[C][K]||(q[C][K]=new d(v.stackLabels,hc,K,m)),q[C][K].setTotal(B)):
z&&(B=e.modifyValue(B)),A||(f[c+1]||K)>=T.min&&(f[c-1]||K)<=T.max))if(K=B.length)for(;K--;)null!==B[K]&&(o[u++]=B[K]);else o[u++]=B;!Ma&&o.length&&(E=Ta(p(E,o[0]),Gb(o)),N=W(p(N,o[0]),tb(o)));e.useThreshold&&null!==x&&(E>=x?(E=x,Qa=!0):N<x&&(N=x,Sa=!0))}}})}function f(a){var b;b=a;Fa=p(Fa,ka.pow(10,Ua(ka.log(fa)/ka.LN10)));1>Fa&&(b=10*w(1/Fa),b=w(a*b)/b);return b}function g(a){var b,c,d=v.tickInterval,e=v.tickPixelInterval;a&&x.beforeSetTickPositions&&x.beforeSetTickPositions();ga?(c=m[j?"xAxis":
"yAxis"][v.linkedTo],b=c.getExtremes(),G=p(b.min,b.dataMin),H=p(b.max,b.dataMax)):(G=p(Y,v.min,E),H=p(aa,v.max,N));A&&(G=qb(G),H=qb(H));ea&&(Y=G=H-ea,aa=H,a&&(ea=null));var h;b=(x.pointRange||0)/2;var k=N-E>Na,i;a&&Na===ha&&(Na=j&&!r(v.min)&&!r(v.max)?Ta(5*x.closestPointRange,N-E):null);H-G<Na&&(h=(Na-H+G)/2,h=[G-h,p(v.min,G-h)],k&&(h[2]=E-b),G=tb(h),i=[G+Na,p(v.max,G+Na)],k&&(i[2]=N+b),H=Gb(i),H-G<Na&&(h[0]=H-Na,h[1]=p(v.min,H-Na),G=tb(h)));if(!Pa&&!Ma&&!ga&&r(G)&&r(H)){b=H-G||1;if(!r(v.min)&&!r(Y)&&
Ga&&(0>E||!Qa))G-=b*Ga;if(!r(v.max)&&!r(aa)&&Ha&&(0<N||!Sa))H+=b*Ha}fa=G===H||void 0===G||void 0===H?1:ga&&!d&&e===c.options.tickPixelInterval?c.tickInterval:p(d,Pa?1:(H-G)*e/(T||1));a&&x.postProcessTickInterval&&(fa=x.postProcessTickInterval(fa));C||(Fa=ka.pow(10,Ua(ka.log(fa)/ka.LN10)),r(v.tickInterval)||(fa=rc(fa,null,Fa,v)));x.tickInterval=fa;Ra="auto"===v.minorTickInterval&&fa?fa/5:v.minorTickInterval;R=v.tickPositions||$a&&$a.apply(x,[G,H]);if(!R)if(C){var l=G,K=H,B=v.startOfWeek;c=[];e={};
b=Oa.global.useUTC;i=v.units||[[ic,[1,2,5,10,20,25,50,100,200,500]],[Wb,[1,2,5,10,15,30]],[Lb,[1,2,5,10,15,30]],[wb,[1,2,3,4,6,8,12]],[hb,[1,2]],[Mb,[1,2]],[xb,[1,2,3,4,6]],[lb,null]];k=i[i.length-1];h=$[k[0]];for(var n=k[1],d=0;d<i.length&&!(k=i[d],h=$[k[0]],n=k[1],i[d+1]&&fa<=(h*n[n.length-1]+$[i[d+1][0]])/2);d++);h===$[lb]&&fa<5*h&&(n=[1,2,5]);i=rc(fa/h,n);var na,l=new Date(l);l.setMilliseconds(0);h>=$[Wb]&&l.setSeconds(h>=$[Lb]?0:i*Ua(l.getSeconds()/i));if(h>=$[Lb])l[tc](h>=$[wb]?0:i*Ua(l[dc]()/
i));if(h>=$[wb])l[uc](h>=$[hb]?0:i*Ua(l[ec]()/i));if(h>=$[hb])l[gc](h>=$[xb]?1:i*Ua(l[Kb]()/i));h>=$[xb]&&(l[vc](h>=$[lb]?0:i*Ua(l[Tb]()/i)),na=l[Ub]());if(h>=$[lb])l[wc](na-na%i);if(h===$[Mb])l[gc](l[Kb]()-l[fc]()+p(B,1));d=1;na=l[Ub]();B=l.getTime();n=l[Tb]();for(l=l[Kb]();B<K;)c.push(B),h===$[lb]?B=Sb(na+d*i,0):h===$[xb]?B=Sb(na,n+d*i):!b&&(h===$[hb]||h===$[Mb])?B=Sb(na,n,l+d*i*(h===$[hb]?1:7)):(B+=h*i,h<=$[wb]&&0===B%$[hb]&&(e[B]=hb)),d++;c.push(B);c.info={unitName:k[0],unitRange:h,count:i,higherRanks:e,
totalRange:h*i};R=c}else{c=f(Ua(G/fa)*fa);na=f(Xb(H/fa)*fa);for(R=[];c<=na;){R.push(c);c=f(c+fa);if(c===K)break;K=c}}a&&X(x,"afterSetTickPositions",{tickPositions:R});if(!ga&&(a=R[0],na=R[R.length-1],v.startOnTick?G=a:G>a&&R.shift(),v.endOnTick?H=na:H<na&&R.pop(),db||(db={x:0,y:0}),!C&&R.length>db[fb]&&!1!==v.alignTicks))db[fb]=R.length}function h(a){a=(new c(a)).render();ta.push(a);return a}function k(){var a=v.title,d=v.stackLabels,e=v.alternateGridColor,f=v.lineWidth,g,i,j=m.hasRendered&&r(ma)&&
!isNaN(ma),K=(g=x.series.length&&r(G)&&r(H))||p(v.showEmpty,!0);if(g||ga){if(Ra&&!Pa)for(g=G+(R[0]-G)%Ra;g<=H;g+=Ra)ua[g]||(ua[g]=new b(g,"minor")),j&&ua[g].isNew&&ua[g].render(null,!0),ua[g].isActive=!0,ua[g].render();o(R,function(a,c){if(!ga||a>=G&&a<=H)La[a]||(La[a]=new b(a)),j&&La[a].isNew&&La[a].render(c,!0),La[a].isActive=!0,La[a].render(c)});e&&o(R,function(a,b){if(0===b%2&&a<H)za[a]||(za[a]=new c),za[a].options={from:a,to:R[b+1]!==ha?R[b+1]:H,color:e},za[a].render(),za[a].isActive=!0});if(!x._addedPlotLB)o((v.plotLines||
[]).concat(v.plotBands||[]),function(a){h(a)}),x._addedPlotLB=!0}o([La,ua,za],function(a){for(var b in a)a[b].isActive?a[b].isActive=!1:(a[b].destroy(),delete a[b])});f&&(g=s+(n?Da:0)+z,i=sa-yb-(n?eb:0)+z,g=L.crispLine([oa,l?s:g,l?i:y,ba,l?pa-Yb:g,l?i:sa-yb],f),V?V.animate({d:g}):V=L.path(g).attr({stroke:v.lineColor,"stroke-width":f,zIndex:7}).add(),V[K?"show":"hide"]());if(B&&K)K=l?s:y,f=M(a.style.fontSize||12),K={low:K+(l?0:T),middle:K+T/2,high:K+(l?T:0)}[a.align],f=(l?y+eb:s)+(l?1:-1)*(n?-1:1)*
Za+(2===u?f:0),B[B.isNew?"attr":"animate"]({x:l?K:f+(n?Da:0)+z+(a.x||0),y:l?f-(n?eb:0)+z:K+(a.y||0)}),B.isNew=!1;if(d&&d.enabled){var t,C,d=x.stackTotalGroup;if(!d)x.stackTotalGroup=d=L.g("stack-labels").attr({visibility:ab,zIndex:6}).translate(O,I).add();for(t in q)for(C in a=q[t],a)a[C].render(d)}x.isDirty=!1}function i(a){for(var b=ta.length;b--;)ta[b].id===a&&ta[b].destroy()}var j=a.isX,n=a.opposite,l=S?!j:j,u=l?n?0:2:n?1:3,q={},v=D(j?xc:Lc,[Mc,Nc,yc,Oc][u],a),x=this,B,U=v.type,C="datetime"===
U,A="logarithmic"===U,z=v.offset||0,fb=j?"x":"y",T=0,da,xa,Ya,J,s,y,Da,eb,yb,Yb,zb,P,Q,Z,V,E,N,Na=v.minRange||v.maxZoom,ea=v.range,Y,aa,wa,ya,H=null,G=null,ma,Ca,Ga=v.minPadding,Ha=v.maxPadding,Ka=0,ga=r(v.linkedTo),Qa,Sa,Ma,U=v.events,Wa,ta=[],fa,Ra,Fa,R,$a=v.tickPositioner,La={},ua={},za={},Ia,Aa,Za,Pa=v.categories,bb=v.labels.formatter||function(){var a=this.value,b=this.dateTimeLabelFormat;return b?Zb(b,a):0===fa%1E6?a/1E6+"M":0===fa%1E3?a/1E3+"k":!Pa&&1E3<=a?cc(a,0):a},Xa=l&&v.labels.staggerLines,
Ea=v.reversed,Ja=Pa&&"between"===v.tickmarkPlacement?0.5:0;b.prototype={addLabel:function(){var a=this.pos,b=v.labels,c=Pa&&l&&Pa.length&&!b.step&&!b.staggerLines&&!b.rotation&&ia/Pa.length||!l&&ia/2,d=a===R[0],e=a===R[R.length-1],f=Pa&&r(Pa[a])?Pa[a]:a,g=this.label,h;if(C)h=R.info,h=v.dateTimeLabelFormats[h.higherRanks[a]||h.unitName];this.isFirst=d;this.isLast=e;a=bb.call({isFirst:d,isLast:e,dateTimeLabelFormat:h,value:A?qc(f):f});c=c&&{width:W(1,w(c-2*(b.padding||10)))+qa};c=F(c,b.style);r(g)?
g&&g.attr({text:a}).css(c):this.label=r(a)&&b.enabled?L.text(a,0,0,b.useHTML).attr({align:b.align,rotation:b.rotation}).css(c).add(Q):null},getLabelSize:function(){var a=this.label;return a?(this.labelBBox=a.getBBox())[l?"height":"width"]:0},render:function(a,b){var c=this.type,d=this.label,e=this.pos,f=v.labels,g=this.gridLine,h=c?c+"Grid":"grid",i=c?c+"Tick":"tick",k=v[h+"LineWidth"],j=v[h+"LineColor"],K=v[h+"LineDashStyle"],m=v[i+"Length"],h=v[i+"Width"]||0,B=v[i+"Color"],x=v[i+"Position"],i=this.mark,
na=f.step,o=b&&cb||sa,t;t=l?zb(e+Ja,null,null,b)+Ya:s+z+(n?(b&&gb||pa)-Yb-s:0);o=l?o-yb+z-(n?eb:0):o-zb(e+Ja,null,null,b)-Ya;if(k){e=P(e+Ja,k,b);if(g===ha){g={stroke:j,"stroke-width":k};if(K)g.dashstyle=K;if(!c)g.zIndex=1;this.gridLine=g=k?L.path(e).attr(g).add(Z):null}!b&&g&&e&&g.animate({d:e})}if(h)"inside"===x&&(m=-m),n&&(m=-m),c=L.crispLine([oa,t,o,ba,t+(l?0:-m),o+(l?m:0)],h),i?i.animate({d:c}):this.mark=L.path(c).attr({stroke:B,"stroke-width":h}).add(Q);d&&!isNaN(t)&&(t=t+f.x-(Ja&&l?Ja*xa*(Ea?
-1:1):0),o=o+f.y-(Ja&&!l?Ja*xa*(Ea?1:-1):0),r(f.y)||(o+=0.9*M(d.styles.lineHeight)-d.getBBox().height/2),Xa&&(o+=16*(a/(na||1)%Xa)),this.isFirst&&!p(v.showFirstLabel,1)||this.isLast&&!p(v.showLastLabel,1)?d.hide():d.show(),na&&a%na&&d.hide(),d[this.isNew?"attr":"animate"]({x:t,y:o}));this.isNew=!1},destroy:function(){Hb(this)}};c.prototype={render:function(){var a=this,b=a.options,c=b.label,d=a.label,e=b.width,f=b.to,g=b.from,h=b.value,i,k=b.dashStyle,j=a.svgElem,m=[],K,B,n=b.color;B=b.zIndex;var x=
b.events;A&&(g=qb(g),f=qb(f),h=qb(h));if(e){if(m=P(h,e),b={stroke:n,"stroke-width":e},k)b.dashstyle=k}else if(r(g)&&r(f))g=W(g,G),f=Ta(f,H),i=P(f),(m=P(g))&&i?m.push(i[4],i[5],i[1],i[2]):m=null,b={fill:n};else return;if(r(B))b.zIndex=B;if(j)m?j.animate({d:m},null,j.onGetPath):(j.hide(),j.onGetPath=function(){j.show()});else if(m&&m.length&&(a.svgElem=j=L.path(m).attr(b).add(),x))for(K in k=function(b){j.on(b,function(c){x[b].apply(a,[c])})},x)k(K);if(c&&r(c.text)&&m&&m.length&&0<Da&&0<eb){c=D({align:l&&
i&&"center",x:l?!i&&4:10,verticalAlign:!l&&i&&"middle",y:l?i?16:10:i?6:-4,rotation:l&&!i&&90},c);if(!d)a.label=d=L.text(c.text,0,0).attr({align:c.textAlign||c.align,rotation:c.rotation,zIndex:B}).css(c.style).add();i=[m[1],m[4],p(m[6],m[1])];m=[m[2],m[5],p(m[7],m[2])];K=Gb(i);B=Gb(m);d.align(c,!1,{x:K,y:B,width:tb(i)-K,height:tb(m)-B});d.show()}else d&&d.hide();return a},destroy:function(){Hb(this);rb(ta,this)}};d.prototype={destroy:function(){Hb(this)},setTotal:function(a){this.cum=this.total=a},
render:function(a){var b=this.options.formatter.call(this);this.label?this.label.attr({text:b,visibility:Va}):this.label=m.renderer.text(b,0,0).css(this.options.style).attr({align:this.textAlign,rotation:this.options.rotation,visibility:Va}).add(a)},setOffset:function(a,b){var c=this.isNegative,d=x.translate(this.total),e=x.translate(0),e=va(d-e),f=m.xAxis[0].translate(this.x)+a,g=m.plotHeight,c={x:S?c?d:d-e:f,y:S?g-f-b:c?g-d-e:g-d,width:S?e:b,height:S?b:e};this.label&&this.label.align(this.alignOptions,
null,c).attr({visibility:ab})}};zb=function(a,b,c,d,e){var f=1,g=0,h=d?J:xa,d=d?ma:G,e=v.ordinal||A&&e;h||(h=xa);c&&(f*=-1,g=T);Ea&&(f*=-1,g-=f*T);b?(Ea&&(a=T-a),a=a/h+d,e&&(a=x.lin2val(a))):(e&&(a=x.val2lin(a)),a=f*(a-d)*h+g+f*Ka);return a};P=function(a,b,c){var d,e,f,a=zb(a,null,null,c),g=c&&cb||sa,h=c&&gb||pa,i,c=e=w(a+Ya);d=f=w(g-a-Ya);if(isNaN(a))i=!0;else if(l){if(d=y,f=g-yb,c<s||c>s+Da)i=!0}else if(c=s,e=h-Yb,d<y||d>y+eb)i=!0;return i?null:L.crispLine([oa,c,d,ba,e,f],b||0)};ra.push(x);m[j?
"xAxis":"yAxis"].push(x);S&&j&&Ea===ha&&(Ea=!0);F(x,{addPlotBand:h,addPlotLine:h,adjustTickAmount:function(){if(db&&db[fb]&&!C&&!Pa&&!ga&&!1!==v.alignTicks){var a=Ia,b=R.length;Ia=db[fb];if(b<Ia){for(;R.length<Ia;)R.push(f(R[R.length-1]+fa));xa*=(b-1)/(Ia-1);H=R[R.length-1]}if(r(a)&&Ia!==a)x.isDirty=!0}},categories:Pa,getExtremes:function(){return{min:G,max:H,dataMin:E,dataMax:N,userMin:Y,userMax:aa}},getPlotLinePath:P,getThreshold:function(a){G>a||null===a?a=G:H<a&&(a=H);return zb(a,0,1)},isXAxis:j,
options:v,plotLinesAndBands:ta,getOffset:function(){var a=x.series.length&&r(G)&&r(H),c=a||p(v.showEmpty,!0),d=0,e=0,f=v.title,g=v.labels,h=[-1,1,1,-1][u],i;Q||(Q=L.g("axis").attr({zIndex:7}).add(),Z=L.g("grid").attr({zIndex:v.gridZIndex||1}).add());Aa=0;if(a||ga)o(R,function(a){La[a]?La[a].addLabel():La[a]=new b(a)}),o(R,function(a){if(0===u||2===u||{1:"left",3:"right"}[u]===g.align)Aa=W(La[a].getLabelSize(),Aa)}),Xa&&(Aa+=16*(Xa-1));else for(i in La)La[i].destroy(),delete La[i];if(f&&f.text){if(!B)B=
x.axisTitle=L.text(f.text,0,0,f.useHTML).attr({zIndex:7,rotation:f.rotation||0,align:f.textAlign||{low:"left",middle:"center",high:"right"}[f.align]}).css(f.style).add(),B.isNew=!0;c&&(d=B.getBBox()[l?"height":"width"],e=p(f.margin,l?5:10));B[c?"show":"hide"]()}z=h*p(v.offset,la[u]);Za=p(f.offset,Aa+e+(2!==u&&Aa&&h*v.labels[l?"y":"x"]));la[u]=W(la[u],Za+d+h*z)},render:k,setAxisSize:function(){var a=v.offsetLeft||0,b=v.offsetRight||0,c=H-G,d=0,e,f;s=p(v.left,O+a);y=p(v.top,I);Da=p(v.width,ia-a+b);
eb=p(v.height,ja);yb=sa-eb-y;Yb=pa-Da-s;T=l?Da:eb;if(j){o(x.series,function(a){d=W(d,a.pointRange);f=a.closestPointRange;!a.noSharedTooltip&&r(f)&&(e=r(e)?Ta(e,f):f)});if((r(Y)||r(aa))&&d>fa/2)d=0;x.pointRange=d;x.closestPointRange=e}x.translationSlope=xa=T/(c+d||1);Ya=l?s:yb;Ka=xa*(d/2);x.left=s;x.top=y;x.len=T},setCategories:function(b,c){x.categories=a.categories=Pa=b;o(x.series,function(a){a.translate();a.setTooltipPoints(!0)});x.isDirty=!0;p(c,!0)&&m.redraw()},setExtremes:function(a,b,c,d){c=
p(c,!0);X(x,"setExtremes",{min:a,max:b},function(){Y=a;aa=b;c&&m.redraw(d)});X(x,"afterSetExtremes",{min:G,max:H})},setScale:function(){var a,b,c;ma=G;Ca=H;da=T;T=l?Da:eb;o(x.series,function(a){if(a.isDirtyData||a.isDirty||a.xAxis.isDirty)c=!0});if(T!==da||c||ga||Y!==wa||aa!==ya){e();g();wa=Y;ya=aa;J=xa;x.translationSlope=xa=T/(H-G+(x.pointRange||0)||1);if(!j)for(a in q)for(b in q[a])q[a][b].cum=q[a][b].total;if(!x.isDirty)x.isDirty=m.isDirtyBox||G!==ma||H!==Ca}},setTickPositions:g,translate:zb,redraw:function(){ib.resetTracker&&
ib.resetTracker();v.ordinal&&g(!0);k();o(ta,function(a){a.render()});o(x.series,function(a){a.isDirty=!0})},removePlotBand:i,removePlotLine:i,reversed:Ea,series:[],stacks:q,destroy:function(){var a;Ba(x);for(a in q)Hb(q[a]),q[a]=null;if(x.stackTotalGroup)x.stackTotalGroup=x.stackTotalGroup.destroy();o([La,ua,za,ta],function(a){Hb(a)});o([V,Q,Z,B],function(a){a&&a.destroy()});V=Q=Z=B=null}});for(Wa in U)ca(x,Wa,U[Wa]);if(A)x.val2lin=qb,x.lin2val=qc}function d(){var b={};return{add:function(c,d,e,f){b[c]||
(d=L.text(d,0,0).css(a.toolbar.itemStyle).align({align:"right",x:-V-20,y:I+30}).on("click",f).attr({align:"right",zIndex:20}).add(),b[c]=d)},remove:function(a){vb(b[a].element);b[a]=null}}}function e(a){function b(){var a=this.points||sb(this),c=a[0].series,d;d=[c.tooltipHeaderFormatter(a[0].key)];o(a,function(a){c=a.series;d.push(c.tooltipFormatter&&c.tooltipFormatter(a)||a.point.tooltipFormatter(c.tooltipOptions.pointFormat))});return d.join("")}function c(a,b){n=l?a:(2*n+a)/3;t=l?b:(t+b)/2;q.attr({x:n,
y:t});Ja=1<va(a-n)||1<va(b-t)?function(){c(a,b)}:null}function d(){if(!l){var a=m.hoverPoints;q.hide();a&&o(a,function(a){a.setState()});m.hoverPoints=null;l=!0}}var e,f=a.borderWidth,g=a.crosshairs,h=[],i=a.style,k=a.shared,j=M(i.padding),l=!0,n=0,t=0;i.padding=0;var q=L.label("",0,0).attr({padding:j,fill:a.backgroundColor,"stroke-width":f,r:a.borderRadius,zIndex:8}).css(i).hide().add().shadow(a.shadow);return{shared:k,refresh:function(f){var i,j,n,t,u={},C=[];n=f.tooltipPos;i=a.formatter||b;u=m.hoverPoints;
k&&(!f.series||!f.series.noSharedTooltip)?(t=0,u&&o(u,function(a){a.setState()}),m.hoverPoints=f,o(f,function(a){a.setState(Qa);t+=a.plotY;C.push(a.getLabelConfig())}),j=f[0].plotX,t=w(t)/f.length,u={x:f[0].category},u.points=C,f=f[0]):u=f.getLabelConfig();u=i.call(u);e=f.series;j=p(j,f.plotX);t=p(t,f.plotY);i=w(n?n[0]:S?ia-t:j);j=w(n?n[1]:S?ja-j:t);n=k||!f.series.isCartesian||mb(i,j);!1===u||!n?d():(l&&(q.show(),l=!1),q.attr({text:u}),q.attr({stroke:a.borderColor||f.color||e.color||"#606060"}),j=
Jc(q.width,q.height,O,I,ia,ja,{x:i,y:j},p(a.distance,12)),c(w(j.x),w(j.y)));if(g){g=sb(g);for(j=g.length;j--;)if(n=f.series[j?"yAxis":"xAxis"],g[j]&&n)if(n=n.getPlotLinePath(f[j?"y":"x"],1),h[j])h[j].attr({d:n,visibility:ab});else{i={"stroke-width":g[j].width||1,stroke:g[j].color||"#C0C0C0",zIndex:g[j].zIndex||2};if(g[j].dashStyle)i.dashstyle=g[j].dashStyle;h[j]=L.path(n).attr(i).add()}}},hide:d,hideCrosshairs:function(){o(h,function(a){a&&a.hide()})},destroy:function(){o(h,function(a){a&&a.destroy()});
q&&(q=q.destroy())}}}function f(a){function b(a){var c,d=zc&&s.width/s.body.scrollWidth-1,e,f,g,a=a||wa.event;if(!a.target)a.target=a.srcElement;if(a.originalEvent)a=a.originalEvent;if(a.event)a=a.event;c=a.touches?a.touches.item(0):a;Wa=Ac(J);e=Wa.left;f=Wa.top;Rb?(g=a.x,c=a.y):(g=c.pageX-e,c=c.pageY-f);d&&(g+=w((d+1)*e-e),c+=w((d+1)*f-f));return F(a,{chartX:g,chartY:c})}function c(a){var b={xAxis:[],yAxis:[]};o(ra,function(c){var d=c.translate,e=c.isXAxis;b[e?"xAxis":"yAxis"].push({axis:c,value:d((S?
!e:e)?a.chartX-O:ja-a.chartY+I,!0)})});return b}function d(){var a=m.hoverSeries,b=m.hoverPoint;if(b)b.onMouseOut();if(a)a.onMouseOut();Xa&&(Xa.hide(),Xa.hideCrosshairs());pb=null}function f(){if(l){var a={xAxis:[],yAxis:[]},b=l.getBBox(),c=b.x-O,d=b.y-I;k&&(o(ra,function(e){if(!1!==e.options.zoomEnabled){var f=e.translate,g=e.isXAxis,h=S?!g:g,i=f(h?c:ja-d-b.height,!0,0,0,1),f=f(h?c+b.width:ja-d,!0,0,0,1);a[g?"xAxis":"yAxis"].push({axis:e,min:Ta(i,f),max:W(i,f)})}}),X(m,"selection",a,jc));l=l.destroy()}y(J,
{cursor:"auto"});m.mouseIsDown=Ia=k=!1;Ba(s,Ma?"touchend":"mouseup",f)}function g(a){var b=r(a.pageX)?a.pageX:a.page.x,a=r(a.pageX)?a.pageY:a.page.y;Wa&&!mb(b-Wa.left-O,a-Wa.top-I)&&d()}function h(){d();Wa=null}var i,j,k,l,n=t.zoomType,q=/x/.test(n),u=/y/.test(n),C=q&&!S||u&&S,p=u&&!S||q&&S;ua=function(){Nb?(Nb.translate(O,I),S&&Nb.attr({width:m.plotWidth,height:m.plotHeight}).invert()):m.trackerGroup=Nb=L.g("tracker").attr({zIndex:9}).add()};ua();if(a.enabled)m.tooltip=Xa=e(a);(function(){J.onmousedown=
function(a){a=b(a);!Ma&&a.preventDefault&&a.preventDefault();m.mouseIsDown=Ia=!0;m.mouseDownX=i=a.chartX;j=a.chartY;ca(s,Ma?"touchend":"mouseup",f)};var e=function(c){if(!c||!(c.touches&&1<c.touches.length)){c=b(c);if(!Ma)c.returnValue=!1;var d=c.chartX,e=c.chartY,f=!mb(d-O,e-I);Ma&&"touchstart"===c.type&&(P(c.target,"isTracker")?m.runTrackerClick||c.preventDefault():!ob&&!f&&c.preventDefault());f&&(d<O?d=O:d>O+ia&&(d=O+ia),e<I?e=I:e>I+ja&&(e=I+ja));if(Ia&&"touchstart"!==c.type){if(k=Math.sqrt(Math.pow(i-
d,2)+Math.pow(j-e,2)),10<k){var g=mb(i-O,j-I);if(Ab&&(q||u)&&g)l||(l=L.rect(O,I,C?1:ia,p?1:ja,0).attr({fill:t.selectionMarkerFill||"rgba(69,114,167,0.25)",zIndex:7}).add());l&&C&&(c=d-i,l.attr({width:va(c),x:(0<c?0:c)+i}));l&&p&&(e-=j,l.attr({height:va(e),y:(0<e?0:e)+j}));g&&!l&&t.panning&&m.pan(d)}}else if(!f){var h,d=m.hoverPoint,e=m.hoverSeries,n,o,g=pa,U=S?c.chartY:c.chartX-O;if(Xa&&a.shared&&(!e||!e.noSharedTooltip)){h=[];n=Q.length;for(o=0;o<n;o++)if(Q[o].visible&&!1!==Q[o].options.enableMouseTracking&&
!Q[o].noSharedTooltip&&Q[o].tooltipPoints.length)c=Q[o].tooltipPoints[U],c._dist=va(U-c.plotX),g=Ta(g,c._dist),h.push(c);for(n=h.length;n--;)h[n]._dist>g&&h.splice(n,1);if(h.length&&h[0].plotX!==pb)Xa.refresh(h),pb=h[0].plotX}if(e&&e.tracker&&(c=e.tooltipPoints[U])&&c!==d)c.onMouseOver()}return f||!Ab}};J.onmousemove=e;ca(J,"mouseleave",h);ca(s,"mousemove",g);J.ontouchstart=function(a){if(q||u)J.onmousedown(a);e(a)};J.ontouchmove=e;J.ontouchend=function(){k&&d()};J.onclick=function(a){var d=m.hoverPoint,
a=b(a);a.cancelBubble=!0;if(!k)if(d&&P(a.target,"isTracker")){var e=d.plotX,f=d.plotY;F(d,{pageX:Wa.left+O+(S?ia-f:e),pageY:Wa.top+I+(S?ja-e:f)});X(d.series,"click",F(a,{point:d}));d.firePointEvent("click",a)}else F(a,c(a)),mb(a.chartX-O,a.chartY-I)&&X(m,"click",a);k=!1}})();Fb=setInterval(function(){Ja&&Ja()},32);F(this,{zoomX:q,zoomY:u,resetTracker:d,normalizeMouseEvent:b,destroy:function(){if(m.trackerGroup)m.trackerGroup=Nb=m.trackerGroup.destroy();Ba(J,"mouseleave",h);Ba(s,"mousemove",g);J.onclick=
J.onmousedown=J.onmousemove=J.ontouchstart=J.ontouchend=J.ontouchmove=null}})}function g(a){var b=a.type||t.type||t.defaultSeriesType,c=ga[b],d=m.hasRendered;if(d)if(S&&"column"===b)c=ga.bar;else if(!S&&"bar"===b)c=ga.column;b=new c;b.init(m,a);!d&&b.inverted&&(S=!0);if(b.isCartesian)Ab=b.isCartesian;Q.push(b);return b}function h(){!1!==t.alignTicks&&o(ra,function(a){a.adjustTickAmount()});db=null}function i(a){var b=m.isDirtyLegend,c,d=m.isDirtyBox,e=Q.length,f=e,g=m.clipRect;for(ub(a,m);f--;)if(a=
Q[f],a.isDirty&&a.options.stacking){c=!0;break}if(c)for(f=e;f--;)if(a=Q[f],a.options.stacking)a.isDirty=!0;o(Q,function(a){a.isDirty&&"point"===a.options.legendType&&(b=!0)});if(b&&Ob.renderLegend)Ob.renderLegend(),m.isDirtyLegend=!1;Ab&&(Bb||(db=null,o(ra,function(a){a.setScale()})),h(),Pb(),o(ra,function(a){a.isDirty&&a.redraw()}));d&&(kc(),ua(),g&&(Cb(g),g.animate({width:m.plotSizeX,height:m.plotSizeY+1})));o(Q,function(a){a.isDirty&&a.visible&&(!a.isCartesian||a.xAxis)&&a.redraw()});ib&&ib.resetTracker&&
ib.resetTracker();X(m,"redraw")}function j(){var b=a.xAxis||{},d=a.yAxis||{},b=sb(b);o(b,function(a,b){a.index=b;a.isX=!0});d=sb(d);o(d,function(a,b){a.index=b});b=b.concat(d);o(b,function(a){new c(a)});h()}function k(b,c){E=D(a.title,b);Y=D(a.subtitle,c);o([["title",b,E],["subtitle",c,Y]],function(a){var b=a[0],c=m[b],d=a[1],a=a[2];c&&d&&(c=c.destroy());a&&a.text&&!c&&(m[b]=L.text(a.text,0,0,a.useHTML).attr({align:a.align,"class":ta+b,zIndex:1}).css(a.style).add().align(a,!1,N))})}function n(){Ca=
t.renderTo;Ka=ta+lc++;jb(Ca)&&(Ca=s.getElementById(Ca));Ca.innerHTML="";Ca.offsetWidth||(ea=Ca.cloneNode(0),y(ea,{position:nb,top:"-9999px",display:""}),s.body.appendChild(ea));Ha=(ea||Ca).offsetWidth;Ga=(ea||Ca).offsetHeight;m.chartWidth=pa=t.width||Ha||600;m.chartHeight=sa=t.height||(19<Ga?Ga:400);m.container=J=aa(bb,{className:ta+"container"+(t.className?" "+t.className:""),id:Ka},F({position:Bc,overflow:Va,width:pa+qa,height:sa+qa,textAlign:"left",lineHeight:"normal"},t.style),ea||Ca);m.renderer=
L=t.forExport?new $b(J,pa,sa,!0):new ac(J,pa,sa);var a,b;Cc&&J.getBoundingClientRect&&(a=function(){y(J,{left:0,top:0});b=J.getBoundingClientRect();y(J,{left:-(b.left-M(b.left))+qa,top:-(b.top-M(b.top))+qa})},a(),ca(wa,"resize",a),ca(m,"destroy",function(){Ba(wa,"resize",a)}))}function l(){function a(){var c=t.width||Ca.offsetWidth,d=t.height||Ca.offsetHeight;if(c&&d){if(c!==Ha||d!==Ga)clearTimeout(b),b=setTimeout(function(){mc(c,d,!1)},100);Ha=c;Ga=d}}var b;ca(wa,"resize",a);ca(m,"destroy",function(){Ba(wa,
"resize",a)})}function q(){m&&X(m,"endResize",null,function(){Bb-=1})}function fb(){for(var b=S||t.inverted||"bar"===t.type||"bar"===t.defaultSeriesType,c=a.series,d=c&&c.length;!b&&d--;)"bar"===c[d].type&&(b=!0);m.inverted=S=b}function z(){var b=a.labels,c=a.credits,e;k();Ob=m.legend=new Vb;o(ra,function(a){a.setScale()});Pb();o(ra,function(a){a.setTickPositions(!0)});h();Pb();kc();Ab&&o(ra,function(a){a.render()});if(!m.seriesGroup)m.seriesGroup=L.g("series-group").attr({zIndex:3}).add();o(Q,function(a){a.translate();
a.setTooltipPoints();a.render()});b.items&&o(b.items,function(){var a=F(b.style,this.style),c=M(a.left)+O,d=M(a.top)+I+12;delete a.left;delete a.top;L.text(this.html,c,d).attr({zIndex:2}).css(a).add()});if(!m.toolbar)m.toolbar=d();if(c.enabled&&!m.credits)e=c.href,m.credits=L.text(c.text,0,0).on("click",function(){if(e)location.href=e}).attr({align:c.position.align,zIndex:8}).css(c.style).add().align(c.position);ua();m.hasRendered=!0;ea&&(Ca.appendChild(J),vb(ea))}function da(){if(!Qb&&wa==wa.top&&
"complete"!==s.readyState)s.attachEvent("onreadystatechange",function(){s.detachEvent("onreadystatechange",da);"complete"===s.readyState&&da()});else{n();X(m,"init");if(Highcharts.RangeSelector&&a.rangeSelector.enabled)m.rangeSelector=new Highcharts.RangeSelector(m);nc();oc();fb();j();o(a.series||[],function(a){g(a)});if(Highcharts.Scroller&&(a.navigator.enabled||a.scrollbar.enabled))m.scroller=new Highcharts.Scroller(m);m.render=z;m.tracker=ib=new f(a.tooltip);z();b&&b.apply(m,[m]);o(m.callbacks,
function(a){a.apply(m,[m])});X(m,"load")}}var A=a.series;a.series=null;a=D(Oa,a);a.series=A;var t=a.chart,A=t.margin,A=Aa(A)?A:[A,A,A,A],u=p(t.marginTop,A[0]),U=p(t.marginRight,A[1]),T=p(t.marginBottom,A[2]),xa=p(t.marginLeft,A[3]),Da=t.spacingTop,C=t.spacingRight,Ya=t.spacingBottom,Na=t.spacingLeft,N,E,Y,I,V,Z,O,la,Ca,ea,J,Ka,Ha,Ga,pa,sa,gb,cb,Db,Sa,$a,Eb,m=this,ob=(A=t.events)&&!!A.click,za,mb,Xa,Ia,Ea,kb,Za,ja,ia,ib,Nb,ua,Ob,Ra,Fa,Wa,Ab=t.showAxes,Bb=0,ra=[],db,Q=[],S,L,Ja,Fb,pb,kc,Pb,nc,oc,mc,
jc,Jb,Vb=function(){function a(b,c){var d=b.legendItem,e=b.legendLine,g=b.legendSymbol,h=t.color,i=c?f.itemStyle.color:h,h=c?b.color:h;d&&d.css({fill:i});e&&e.attr({stroke:h});g&&g.attr({stroke:h,fill:h})}function b(a,c,d){var e=a.legendItem,f=a.legendLine,g=a.legendSymbol,a=a.checkbox;e&&e.attr({x:c,y:d});f&&f.translate(c,d-4);g&&g.attr({x:c+g.xOff,y:d+g.yOff});if(a)a.x=c,a.y=d}function c(){o(j,function(a){var b=a.checkbox,c=w.alignAttr;b&&y(b,{left:c.translateX+a.legendItemWidth+b.x-40+qa,top:c.translateY+
b.y-11+qa})})}function d(c){var e,j,k,m,o=c.legendItem;m=c.series||c;var u=m.options,v=u&&u.borderWidth||0;if(!o){m=/^(bar|pie|area|column)$/.test(m.type);c.legendItem=o=L.text(f.labelFormatter.call(c),0,0).css(c.visible?l:t).on("mouseover",function(){c.setState(Qa);o.css(n)}).on("mouseout",function(){o.css(c.visible?l:t);c.setState()}).on("click",function(){var a=function(){c.setVisible()};c.firePointEvent?c.firePointEvent("legendItemClick",null,a):X(c,"legendItemClick",null,a)}).attr({zIndex:2}).add(w);
if(!m&&u&&u.lineWidth){var r={"stroke-width":u.lineWidth,zIndex:2};if(u.dashStyle)r.dashstyle=u.dashStyle;c.legendLine=L.path([oa,-h-i,0,ba,-i,0]).attr(r).add(w)}if(m)k=L.rect(e=-h-i,j=-11,h,12,2).attr({zIndex:3}).add(w);else if(u&&u.marker&&u.marker.enabled)k=u.marker.radius,k=L.symbol(c.symbol,e=-h/2-i-k,j=-4-k,2*k,2*k).attr(c.pointAttr[ya]).attr({zIndex:3}).add(w);if(k)k.xOff=e+v%2/2,k.yOff=j+v%2/2;c.legendSymbol=k;a(c,c.visible);if(u&&u.showCheckbox)c.checkbox=aa("input",{type:"checkbox",checked:c.selected,
defaultChecked:c.selected},f.itemCheckboxStyle,J),ca(c.checkbox,"click",function(a){X(c,"checkboxClick",{checked:a.target.checked},function(){c.select()})})}e=o.getBBox();j=c.legendItemWidth=f.itemWidth||h+i+e.width+q;A=e.height;if(g&&p-C+j>(Ya||pa-2*q-C))p=C,U+=z+A+fb;T=U+fb;b(c,p,U);g?p+=j:U+=z+A+fb;s=Ya||W(g?p-C:j,s)}function e(){p=C;U=q+z+u-5;T=s=0;w||(w=L.g("legend").attr({zIndex:10}).add());j=[];o(I,function(a){var b=a.options;b.showInLegend&&(j=j.concat("point"===b.legendType?a.data:a))});
Kc(j,function(a,b){return(a.options.legendIndex||0)-(b.options.legendIndex||0)});Da&&j.reverse();o(j,d);Ra=Ya||s;Fa=T-u+A;if(da||xa){Ra+=2*q;Fa+=2*q;if(r){if(0<Ra&&0<Fa)r[r.isNew?"attr":"animate"](r.crisp(null,null,null,Ra,Fa)),r.isNew=!1}else r=L.rect(0,0,Ra,Fa,f.borderRadius,da||0).attr({stroke:f.borderColor,"stroke-width":da||0,fill:xa||ma}).add(w).shadow(f.shadow),r.isNew=!0;r[j.length?"show":"hide"]()}for(var a=["left","right","top","bottom"],b,g=4;g--;)b=a[g],k[b]&&"auto"!==k[b]&&(f[2>g?"align":
"verticalAlign"]=b,f[2>g?"x":"y"]=M(k[b])*(g%2?-1:1));j.length&&w.align(F(f,{width:Ra,height:Fa}),!0,N);Bb||c()}var f=m.options.legend;if(f.enabled){var g="horizontal"===f.layout,h=f.symbolWidth,i=f.symbolPadding,j,k=f.style,l=f.itemStyle,n=f.itemHoverStyle,t=D(l,f.itemHiddenStyle),q=f.padding||M(k.padding),u=18,C=4+q+h+i,p,U,T,A=0,z=f.itemMarginTop||0,fb=f.itemMarginBottom||0,r,da=f.borderWidth,xa=f.backgroundColor,w,s,Ya=f.width,I=m.series,Da=f.reversed;e();ca(m,"endResize",c);return{colorizeItem:a,
destroyItem:function(a){var b=a.checkbox;o(["legendItem","legendLine","legendSymbol"],function(b){a[b]&&a[b].destroy()});b&&vb(a.checkbox)},renderLegend:e,destroy:function(){r&&(r=r.destroy());w&&(w=w.destroy())}}}};mb=function(a,b){return 0<=a&&a<=ia&&0<=b&&b<=ja};Jb=function(){X(m,"selection",{resetSelection:!0},jc);m.toolbar.remove("zoom")};jc=function(a){var b=Oa.lang,c=100>m.pointCount;!1!==m.resetZoomEnabled&&m.toolbar.add("zoom",b.resetZoom,b.resetZoomTitle,Jb);!a||a.resetSelection?o(ra,function(a){!1!==
a.options.zoomEnabled&&a.setExtremes(null,null,!0,c)}):o(a.xAxis.concat(a.yAxis),function(a){var b=a.axis;m.tracker[b.isXAxis?"zoomX":"zoomY"]&&b.setExtremes(a.min,a.max,!0,c)})};m.pan=function(a){var b=m.xAxis[0],c=m.mouseDownX,d=b.pointRange/2,e=b.getExtremes(),f=b.translate(c-a,!0)+d,c=b.translate(c+ia-a,!0)-d;(d=m.hoverPoints)&&o(d,function(a){a.setState()});f>Ta(e.dataMin,e.min)&&c<W(e.dataMax,e.max)&&b.setExtremes(f,c,!0,!1);m.mouseDownX=a;y(J,{cursor:"move"})};Pb=function(){var b=a.legend,
c=p(b.margin,10),d=b.x,e=b.y,f=b.align,g=b.verticalAlign,h;nc();if((m.title||m.subtitle)&&!r(u))(h=W(m.title&&!E.floating&&!E.verticalAlign&&E.y||0,m.subtitle&&!Y.floating&&!Y.verticalAlign&&Y.y||0))&&(I=W(I,h+p(E.margin,15)+Da));b.enabled&&!b.floating&&("right"===f?r(U)||(V=W(V,Ra-d+c+C)):"left"===f?r(xa)||(O=W(O,Ra+d+c+Na)):"top"===g?r(u)||(I=W(I,Fa+e+c+Da)):"bottom"===g&&(r(T)||(Z=W(Z,Fa-e+c+Ya))));m.extraBottomMargin&&(Z+=m.extraBottomMargin);m.extraTopMargin&&(I+=m.extraTopMargin);Ab&&o(ra,function(a){a.getOffset()});
r(xa)||(O+=la[3]);r(u)||(I+=la[0]);r(T)||(Z+=la[2]);r(U)||(V+=la[1]);oc()};mc=function(a,b,c){var d=m.title,e=m.subtitle;Bb+=1;ub(c,m);cb=sa;gb=pa;if(r(a))m.chartWidth=pa=w(a);if(r(b))m.chartHeight=sa=w(b);y(J,{width:pa+qa,height:sa+qa});L.setSize(pa,sa,c);ia=pa-O-V;ja=sa-I-Z;db=null;o(ra,function(a){a.isDirty=!0;a.setScale()});o(Q,function(a){a.isDirty=!0});m.isDirtyLegend=!0;m.isDirtyBox=!0;Pb();d&&d.align(null,null,N);e&&e.align(null,null,N);i(c);cb=null;X(m,"resize");!1===Ib?q():setTimeout(q,
Ib&&Ib.duration||500)};oc=function(){m.plotLeft=O=w(O);m.plotTop=I=w(I);m.plotWidth=ia=w(pa-O-V);m.plotHeight=ja=w(sa-I-Z);m.plotSizeX=S?ja:ia;m.plotSizeY=S?ia:ja;N={x:Na,y:Da,width:pa-Na-C,height:sa-Da-Ya};o(ra,function(a){a.isDirty&&a.setAxisSize()})};nc=function(){I=p(u,Da);V=p(U,C);Z=p(T,Ya);O=p(xa,Na);la=[0,0,0,0]};kc=function(){var a=t.borderWidth||0,b=t.backgroundColor,c=t.plotBackgroundColor,d=t.plotBackgroundImage,e,f={x:O,y:I,width:ia,height:ja};e=a+(t.shadow?8:0);if(a||b)Db?Db.animate(Db.crisp(null,
null,null,pa-e,sa-e)):Db=L.rect(e/2,e/2,pa-e,sa-e,t.borderRadius,a).attr({stroke:t.borderColor,"stroke-width":a,fill:b||ma}).add().shadow(t.shadow);c&&(Sa?Sa.animate(f):Sa=L.rect(O,I,ia,ja,0).attr({fill:c}).add().shadow(t.plotShadow));d&&($a?$a.animate(f):$a=L.image(d,O,I,ia,ja).add());t.plotBorderWidth&&(Eb?Eb.animate(Eb.crisp(null,O,I,ia,ja)):Eb=L.rect(O,I,ia,ja,0,t.plotBorderWidth).attr({stroke:t.plotBorderColor,"stroke-width":t.plotBorderWidth,zIndex:4}).add());m.isDirtyBox=!1};!1!==t.reflow&&
ca(m,"load",l);if(A)for(za in A)ca(m,za,A[za]);m.options=a;m.series=Q;m.xAxis=[];m.yAxis=[];m.addSeries=function(a,b,c){var d;a&&(ub(c,m),b=p(b,!0),X(m,"addSeries",{options:a},function(){d=g(a);d.isDirty=!0;m.isDirtyLegend=!0;b&&m.redraw()}));return d};m.animation=p(t.animation,!0);m.Axis=c;m.destroy=function(){var b,c=J&&J.parentNode;if(null!==m){X(m,"destroy");Ba(m);for(b=ra.length;b--;)ra[b]=ra[b].destroy();for(b=Q.length;b--;)Q[b]=Q[b].destroy();o("title,subtitle,seriesGroup,clipRect,credits,tracker,scroller,rangeSelector".split(","),
function(a){var b=m[a];b&&(m[a]=b.destroy())});o([Db,Eb,Sa,Ob,Xa,L,ib],function(a){a&&a.destroy&&a.destroy()});Db=Eb=Sa=Ob=Xa=L=ib=null;if(J)J.innerHTML="",Ba(J),c&&vb(J),J=null;clearInterval(Fb);for(b in m)delete m[b];a=m=null}};m.get=function(a){var b,c,d;for(b=0;b<ra.length;b++)if(ra[b].options.id===a)return ra[b];for(b=0;b<Q.length;b++)if(Q[b].options.id===a)return Q[b];for(b=0;b<Q.length;b++){d=Q[b].points;for(c=0;c<d.length;c++)if(d[c].id===a)return d[c]}return null};m.getSelectedPoints=function(){var a=
[];o(Q,function(b){a=a.concat(pc(b.points,function(a){return a.selected}))});return a};m.getSelectedSeries=function(){return pc(Q,function(a){return a.selected})};m.hideLoading=function(){Ea&&bc(Ea,{opacity:0},{duration:a.loading.hideDuration||100,complete:function(){y(Ea,{display:ma})}});Za=!1};m.initSeries=g;m.isInsidePlot=mb;m.redraw=i;m.setSize=mc;m.setTitle=k;m.showLoading=function(b){var c=a.loading;Ea||(Ea=aa(bb,{className:ta+"loading"},F(c.style,{left:O+qa,top:I+qa,width:ia+qa,height:ja+qa,
zIndex:10,display:ma}),J),kb=aa("span",null,c.labelStyle,Ea));kb.innerHTML=b||a.lang.loading;Za||(y(Ea,{opacity:0,display:""}),bc(Ea,{opacity:c.style.opacity},{duration:c.showDuration||0}),Za=!0)};m.pointCount=0;m.counters=new sc;da()}var s=document,wa=window,ka=Math,w=ka.round,Ua=ka.floor,Xb=ka.ceil,W=ka.max,Ta=ka.min,va=ka.abs,E=ka.cos,Z=ka.sin,Ga=ka.PI,Dc=2*Ga/360,gb=navigator.userAgent,Rb=/msie/i.test(gb)&&!wa.opera,Sa=8===s.documentMode,zc=/AppleWebKit/.test(gb),Cc=/Firefox/.test(gb),Qb=!!s.createElementNS&&
!!s.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,Pc=Cc&&4>parseInt(gb.split("Firefox/")[1],10),ac,Ma=void 0!==s.documentElement.ontouchstart,Ec={},lc=0,Za,Oa,Zb,Ib,$a,$,ha,bb="div",nb="absolute",Bc="relative",Va="hidden",ta="highcharts-",ab="visible",qa="px",ma="none",oa="M",ba="L",Fc="rgba(192,192,192,"+(Qb?1.0E-6:0.0020)+")",ya="",Qa="hover",ic="millisecond",Wb="second",Lb="minute",wb="hour",hb="day",Mb="week",xb="month",lb="year",Sb,dc,ec,fc,Kb,Tb,Ub,tc,uc,gc,vc,wc,ob=wa.HighchartsAdapter,
ea=ob||{},o=ea.each,pc=ea.grep,Ac=ea.offset,ua=ea.map,D=ea.merge,ca=ea.addEvent,Ba=ea.removeEvent,X=ea.fireEvent,bc=ea.animate,Cb=ea.stop,ga={};wa.Highcharts={};Zb=function(a,b,c){function d(a,b){a=a.toString().replace(/^([0-9])$/,"0$1");3===b&&(a=a.toString().replace(/^([0-9]{2})$/,"0$1"));return a}if(!r(b)||isNaN(b))return"Invalid date";var a=p(a,"%Y-%m-%d %H:%M:%S"),e=new Date(b),f,g=e[ec](),h=e[fc](),i=e[Kb](),j=e[Tb](),k=e[Ub](),n=Oa.lang,l=n.weekdays,b={a:l[h].substr(0,3),A:l[h],d:d(i),e:i,
b:n.shortMonths[j],B:n.months[j],m:d(j+1),y:k.toString().substr(2,2),Y:k,H:d(g),I:d(g%12||12),l:g%12||12,M:d(e[dc]()),p:12>g?"AM":"PM",P:12>g?"am":"pm",S:d(e.getSeconds()),L:d(b%1E3,3)};for(f in b)a=a.replace("%"+f,b[f]);return c?a.substr(0,1).toUpperCase()+a.substr(1):a};sc.prototype={wrapColor:function(a){if(this.color>=a)this.color=0},wrapSymbol:function(a){if(this.symbol>=a)this.symbol=0}};$=Ka(ic,1,Wb,1E3,Lb,6E4,wb,36E5,hb,864E5,Mb,6048E5,xb,2592E6,lb,31556952E3);$a={init:function(a,b,c){var b=
b||"",d=a.shift,e=-1<b.indexOf("C"),f=e?7:3,g,b=b.split(" "),c=[].concat(c),h,i,j=function(a){for(g=a.length;g--;)a[g]===oa&&a.splice(g+1,0,a[g+1],a[g+2],a[g+1],a[g+2])};e&&(j(b),j(c));a.isArea&&(h=b.splice(b.length-6,6),i=c.splice(c.length-6,6));1===d&&(c=[].concat(c).splice(0,f).concat(c));a.shift=0;if(b.length)for(a=c.length;b.length<a;)d=[].concat(b).splice(b.length-f,f),e&&(d[f-6]=d[f-2],d[f-5]=d[f-1]),b=b.concat(d);h&&(b=b.concat(h),c=c.concat(i));return[b,c]},step:function(a,b,c,d){var e=[],
f=a.length;if(1===c)e=d;else if(f===b.length&&1>c)for(;f--;)d=parseFloat(a[f]),e[f]=isNaN(d)?a[f]:c*parseFloat(b[f]-d)+d;else e=b;return e}};ob&&ob.init&&ob.init($a);if(!ob&&wa.jQuery){var la=jQuery,o=function(a,b){for(var c=0,d=a.length;c<d;c++)if(!1===b.call(a[c],a[c],c,a))return c},pc=la.grep,ua=function(a,b){for(var c=[],d=0,e=a.length;d<e;d++)c[d]=b.call(a[d],a[d],d,a);return c},D=function(){var a=arguments;return la.extend(!0,null,a[0],a[1],a[2],a[3])},Ac=function(a){return la(a).offset()},
ca=function(a,b,c){la(a).bind(b,c)},Ba=function(a,b,c){var d=s.removeEventListener?"removeEventListener":"detachEvent";s[d]&&!a[d]&&(a[d]=function(){});la(a).unbind(b,c)},X=function(a,b,c,d){var e=la.Event(b),f="detached"+b;F(e,c);a[b]&&(a[f]=a[b],a[b]=null);la(a).trigger(e);a[f]&&(a[b]=a[f],a[f]=null);d&&!e.isDefaultPrevented()&&d(e)},bc=function(a,b,c){var d=la(a);if(b.d)a.toD=b.d,b.d=1;d.stop();d.animate(b,c)},Cb=function(a){la(a).stop()};la.extend(la.easing,{easeOutQuad:function(a,b,c,d,e){return-d*
(b/=e)*(b-2)+c}});var Gc=jQuery.fx,Hc=Gc.step;o(["cur","_default","width","height"],function(a,b){var c=b?Hc:Gc.prototype,d=c[a],e;d&&(c[a]=function(a){a=b?a:this;e=a.elem;return e.attr?e.attr(a.prop,a.now):d.apply(this,arguments)})});Hc.d=function(a){var b=a.elem;if(!a.started){var c=$a.init(b,b.d,b.toD);a.start=c[0];a.end=c[1];a.started=!0}b.attr("d",$a.step(a.start,a.end,a.pos,b.toD))}}var Fb={enabled:!0,align:"center",x:0,y:15,style:{color:"#666",fontSize:"11px",lineHeight:"14px"}};Oa={colors:"#4572A7,#AA4643,#89A54E,#80699B,#3D96AE,#DB843D,#92A8CD,#A47D7C,#B5CA92".split(","),
symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January,February,March,April,May,June,July,August,September,October,November,December".split(","),shortMonths:"Jan,Feb,Mar,Apr,May,June,Jul,Aug,Sep,Oct,Nov,Dec".split(","),weekdays:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),decimalPoint:".",resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:","},global:{useUTC:!0},chart:{borderColor:"#4572A7",borderRadius:5,
defaultSeriesType:"line",ignoreHiddenSeries:!0,spacingTop:10,spacingRight:10,spacingBottom:15,spacingLeft:10,style:{fontFamily:'"Lucida Grande", "Lucida Sans Unicode", Verdana, Arial, Helvetica, sans-serif',fontSize:"12px"},backgroundColor:"#FFFFFF",plotBorderColor:"#C0C0C0"},title:{text:"Chart title",align:"center",y:15,style:{color:"#3E576F",fontSize:"16px"}},subtitle:{text:"",align:"center",y:30,style:{color:"#6D869F"}},plotOptions:{line:{allowPointSelect:!1,showCheckbox:!1,animation:{duration:1E3},
events:{},lineWidth:2,shadow:!0,marker:{enabled:!0,lineWidth:0,radius:4,lineColor:"#FFFFFF",states:{hover:{},select:{fillColor:"#FFFFFF",lineColor:"#000000",lineWidth:2}}},point:{events:{}},dataLabels:D(Fb,{enabled:!1,y:-6,formatter:function(){return this.y}}),cropThreshold:300,pointRange:0,showInLegend:!0,states:{hover:{marker:{}},select:{marker:{}}},stickyTracking:!0}},labels:{style:{position:nb,color:"#3E576F"}},legend:{enabled:!0,align:"center",layout:"horizontal",labelFormatter:function(){return this.name},
borderWidth:1,borderColor:"#909090",borderRadius:5,shadow:!1,style:{padding:"5px"},itemStyle:{cursor:"pointer",color:"#3E576F"},itemHoverStyle:{color:"#000000"},itemHiddenStyle:{color:"#C0C0C0"},itemCheckboxStyle:{position:nb,width:"13px",height:"13px"},symbolWidth:16,symbolPadding:5,verticalAlign:"bottom",x:0,y:0},loading:{labelStyle:{fontWeight:"bold",position:Bc,top:"1em"},style:{position:nb,backgroundColor:"white",opacity:0.5,textAlign:"center"}},tooltip:{enabled:!0,backgroundColor:"rgba(255, 255, 255, .85)",
borderWidth:2,borderRadius:5,headerFormat:'<span style="font-size: 10px">{point.key}</span><br/>',pointFormat:'<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b><br/>',shadow:!0,snap:Ma?25:10,style:{color:"#333333",fontSize:"12px",padding:"5px",whiteSpace:"nowrap"}},toolbar:{itemStyle:{color:"#4572A7",cursor:"pointer"}},credits:{enabled:!0,text:"Highcharts.com",href:"http://www.highcharts.com",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},style:{cursor:"pointer",
color:"#909090",fontSize:"10px"}}};var xc={dateTimeLabelFormats:Ka(ic,"%H:%M:%S.%L",Wb,"%H:%M:%S",Lb,"%H:%M",wb,"%H:%M",hb,"%e. %b",Mb,"%e. %b",xb,"%b '%y",lb,"%Y"),endOnTick:!1,gridLineColor:"#C0C0C0",labels:Fb,lineColor:"#C0D0E0",lineWidth:1,max:null,min:null,minPadding:0.01,maxPadding:0.01,minorGridLineColor:"#E0E0E0",minorGridLineWidth:1,minorTickColor:"#A0A0A0",minorTickLength:2,minorTickPosition:"outside",startOfWeek:1,startOnTick:!1,tickColor:"#C0D0E0",tickLength:5,tickmarkPlacement:"between",
tickPixelInterval:100,tickPosition:"outside",tickWidth:1,title:{align:"middle",style:{color:"#6D869F",fontWeight:"bold"}},type:"linear"},Lc=D(xc,{endOnTick:!0,gridLineWidth:1,tickPixelInterval:72,showLastLabel:!0,labels:{align:"right",x:-8,y:3},lineWidth:0,maxPadding:0.05,minPadding:0.05,startOnTick:!0,tickWidth:0,title:{rotation:270,text:"Y-values"},stackLabels:{enabled:!1,formatter:function(){return this.total},style:Fb.style}}),Oc={labels:{align:"right",x:-8,y:null},title:{rotation:270}},Nc={labels:{align:"left",
x:8,y:null},title:{rotation:90}},yc={labels:{align:"center",x:0,y:14},title:{rotation:0}},Mc=D(yc,{labels:{y:-5}}),Y=Oa.plotOptions,za=Y.line;Y.spline=D(za);Y.scatter=D(za,{lineWidth:0,states:{hover:{lineWidth:0}},tooltip:{headerFormat:'<span style="font-size: 10px; color:{series.color}">{series.name}</span><br/>',pointFormat:"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>"}});Y.area=D(za,{threshold:0});Y.areaspline=D(Y.area);Y.column=D(za,{borderColor:"#FFFFFF",borderWidth:1,borderRadius:0,groupPadding:0.2,
marker:null,pointPadding:0.1,minPointLength:0,cropThreshold:50,pointRange:null,states:{hover:{brightness:0.1,shadow:!1},select:{color:"#C0C0C0",borderColor:"#000000",shadow:!1}},dataLabels:{y:null,verticalAlign:null},threshold:0});Y.bar=D(Y.column,{dataLabels:{align:"left",x:5,y:0}});Y.pie=D(za,{borderColor:"#FFFFFF",borderWidth:1,center:["50%","50%"],colorByPoint:!0,dataLabels:{distance:30,enabled:!0,formatter:function(){return this.point.name},y:5},legendType:"point",marker:null,size:"75%",showInLegend:!1,
slicedOffset:10,states:{hover:{brightness:0.1,shadow:!1}}});Jb();var Ha=function(a){var b=[],c;(function(a){(c=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/.exec(a))?b=[M(c[1]),M(c[2]),M(c[3]),parseFloat(c[4],10)]:(c=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(a))&&(b=[M(c[1],16),M(c[2],16),M(c[3],16),1])})(a);return{get:function(c){return b&&!isNaN(b[0])?"rgb"===c?"rgb("+b[0]+","+b[1]+","+b[2]+")":"a"===c?b[3]:"rgba("+b.join(",")+")":
a},brighten:function(a){if(kb(a)&&0!==a){var c;for(c=0;3>c;c++)b[c]+=M(255*a),0>b[c]&&(b[c]=0),255<b[c]&&(b[c]=255)}return this},setOpacity:function(a){b[3]=a;return this}}};cb.prototype={init:function(a,b){this.element=s.createElementNS("http://www.w3.org/2000/svg",b);this.renderer=a;this.attrSetters={}},animate:function(a,b,c){b=p(b,Ib,!0);Cb(this);if(b){b=D(b);if(c)b.complete=c;bc(this,a,b)}else this.attr(a),c&&c()},attr:function(a,b){var c,d,e,f,g=this.element,h=g.nodeName,i=this.renderer,j,k=
this.attrSetters,n=this.shadows,l=this.htmlNode,o,p=this;jb(a)&&r(b)&&(c=a,a={},a[c]=b);if(jb(a))c=a,"circle"===h?c={x:"cx",y:"cy"}[c]||c:"strokeWidth"===c&&(c="stroke-width"),p=P(g,c)||this[c]||0,"d"!==c&&"visibility"!==c&&(p=parseFloat(p));else for(c in a){j=!1;d=a[c];e=k[c]&&k[c](d,c);if(!1!==e){e!==ha&&(d=e);if("d"===c)d&&d.join&&(d=d.join(" ")),/(NaN| {2}|^$)/.test(d)&&(d="M 0 0"),this.d=d;else if("x"===c&&"text"===h){for(e=0;e<g.childNodes.length;e++)f=g.childNodes[e],P(f,"x")===P(g,"x")&&P(f,
"x",d);this.rotation&&P(g,"transform","rotate("+this.rotation+" "+d+" "+M(a.y||P(g,"y"))+")")}else if("fill"===c)d=i.color(d,g,c);else if("circle"===h&&("x"===c||"y"===c))c={x:"cx",y:"cy"}[c]||c;else if("rect"===h&&"r"===c)P(g,{rx:d,ry:d}),j=!0;else if("translateX"===c||"translateY"===c||"rotation"===c||"verticalAlign"===c)this[c]=d,this.updateTransform(),j=!0;else if("stroke"===c)d=i.color(d,g,c);else if("dashstyle"===c)if(c="stroke-dasharray",d=d&&d.toLowerCase(),"solid"===d)d=ma;else{if(d){d=d.replace("shortdashdotdot",
"3,1,1,1,1,1,").replace("shortdashdot","3,1,1,1").replace("shortdot","1,1,").replace("shortdash","3,1,").replace("longdash","8,3,").replace(/dot/g,"1,3,").replace("dash","4,3,").replace(/,$/,"").split(",");for(e=d.length;e--;)d[e]=M(d[e])*a["stroke-width"];d=d.join(",")}}else"isTracker"===c?this[c]=d:"width"===c?d=M(d):"align"===c?(c="text-anchor",d={left:"start",center:"middle",right:"end"}[d]):"title"===c&&(e=s.createElementNS("http://www.w3.org/2000/svg","title"),e.appendChild(s.createTextNode(d)),
g.appendChild(e));"strokeWidth"===c&&(c="stroke-width");zc&&"stroke-width"===c&&0===d&&(d=1.0E-6);this.symbolName&&/^(x|y|r|start|end|innerR|anchorX|anchorY)/.test(c)&&(o||(this.symbolAttr(a),o=!0),j=!0);if(n&&/^(width|height|visibility|x|y|d|transform)$/.test(c))for(e=n.length;e--;)P(n[e],c,d);if(("width"===c||"height"===c)&&"rect"===h&&0>d)d=0;"text"===c?(this.textStr=d,this.added&&i.buildText(this)):j||P(g,c,d)}if(l&&("x"===c||"y"===c||"translateX"===c||"translateY"===c||"visibility"===c)){e=l.length?
l:[this];f=e.length;var z;for(z=0;z<f;z++)l=e[z],j=l.getBBox(),l=l.htmlNode,y(l,F(this.styles,{left:j.x+(this.translateX||0)+qa,top:j.y+(this.translateY||0)+qa})),"visibility"===c&&y(l,{visibility:d})}}return p},symbolAttr:function(a){var b=this;o("x,y,r,start,end,width,height,innerR,anchorX,anchorY".split(","),function(c){b[c]=p(a[c],b[c])});b.attr({d:b.renderer.symbols[b.symbolName](b.x,b.y,b.width,b.height,b)})},clip:function(a){return this.attr("clip-path","url("+this.renderer.url+"#"+a.id+")")},
crisp:function(a,b,c,d,e){var f,g={},h={},i,a=a||this.strokeWidth||this.attr&&this.attr("stroke-width")||0;i=w(a)%2/2;h.x=Ua(b||this.x||0)+i;h.y=Ua(c||this.y||0)+i;h.width=Ua((d||this.width||0)-2*i);h.height=Ua((e||this.height||0)-2*i);h.strokeWidth=a;for(f in h)this[f]!==h[f]&&(this[f]=g[f]=h[f]);return g},css:function(a){var b=this.element,b=a&&a.width&&"text"===b.nodeName,c,d="",e=function(a,b){return"-"+b.toLowerCase()};if(a&&a.color)a.fill=a.color;this.styles=a=F(this.styles,a);if(Rb&&!Qb)b&&
delete a.width,y(this.element,a);else{for(c in a)d+=c.replace(/([A-Z])/g,e)+":"+a[c]+";";this.attr({style:d})}b&&this.added&&this.renderer.buildText(this);return this},on:function(a,b){var c=b;Ma&&"click"===a&&(a="touchstart",c=function(a){a.preventDefault();b()});this.element["on"+a]=c;return this},translate:function(a,b){return this.attr({translateX:a,translateY:b})},invert:function(){this.inverted=!0;this.updateTransform();return this},updateTransform:function(){var a=this.translateX||0,b=this.translateY||
0,c=this.inverted,d=this.rotation,e=[];c&&(a+=this.attr("width"),b+=this.attr("height"));(a||b)&&e.push("translate("+a+","+b+")");c?e.push("rotate(90) scale(-1,1)"):d&&e.push("rotate("+d+" "+this.x+" "+this.y+")");e.length&&P(this.element,"transform",e.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},align:function(a,b,c){a?(this.alignOptions=a,this.alignByTranslate=b,c||this.renderer.alignedObjects.push(this)):(a=this.alignOptions,b=this.alignByTranslate);
var c=p(c,this.renderer),d=a.align,e=a.verticalAlign,f=(c.x||0)+(a.x||0),g=(c.y||0)+(a.y||0),h={};/^(right|center)$/.test(d)&&(f+=(c.width-(a.width||0))/{right:1,center:2}[d]);h[b?"translateX":"x"]=w(f);/^(bottom|middle)$/.test(e)&&(g+=(c.height-(a.height||0))/({bottom:1,middle:2}[e]||1));h[b?"translateY":"y"]=w(g);this[this.placed?"animate":"attr"](h);this.placed=!0;this.alignAttr=h;return this},getBBox:function(){var a,b,c,d=this.rotation,e=d*Dc;try{a=F({},this.element.getBBox())}catch(f){a={width:0,
height:0}}b=a.width;c=a.height;if(d)a.width=va(c*Z(e))+va(b*E(e)),a.height=va(c*E(e))+va(b*Z(e));return a},show:function(){return this.attr({visibility:ab})},hide:function(){return this.attr({visibility:Va})},add:function(a){var b=this.renderer,c=a||b,d=c.element||b.box,e=d.childNodes,f=this.element,g=P(f,"zIndex"),h;this.parentInverted=a&&a.inverted;void 0!==this.textStr&&b.buildText(this);if(a&&this.htmlNode){if(!a.htmlNode)a.htmlNode=[];a.htmlNode.push(this)}if(g)c.handleZ=!0,g=M(g);if(c.handleZ)for(c=
0;c<e.length;c++)if(a=e[c],b=P(a,"zIndex"),a!==f&&(M(b)>g||!r(g)&&r(b))){d.insertBefore(f,a);h=!0;break}h||d.appendChild(f);this.added=!0;X(this,"add");return this},safeRemoveChild:function(a){var b=a.parentNode;b&&b.removeChild(a)},destroy:function(){var a=this,b=a.element||{},c=a.shadows,d=a.box,e,f;b.onclick=b.onmouseout=b.onmouseover=b.onmousemove=null;Cb(a);if(a.clipPath)a.clipPath=a.clipPath.destroy();if(a.stops){for(f=0;f<a.stops.length;f++)a.stops[f]=a.stops[f].destroy();a.stops=null}a.safeRemoveChild(b);
c&&o(c,function(b){a.safeRemoveChild(b)});d&&d.destroy();rb(a.renderer.alignedObjects,a);for(e in a)delete a[e];return null},empty:function(){for(var a=this.element,b=a.childNodes,c=b.length;c--;)a.removeChild(b[c])},shadow:function(a,b){var c=[],d,e,f=this.element,g=this.parentInverted?"(-1,-1)":"(1,1)";if(a){for(d=1;3>=d;d++)e=f.cloneNode(0),P(e,{isShadow:"true",stroke:"rgb(0, 0, 0)","stroke-opacity":0.05*d,"stroke-width":7-2*d,transform:"translate"+g,fill:ma}),b?b.element.appendChild(e):f.parentNode.insertBefore(e,
f),c.push(e);this.shadows=c}return this}};var $b=function(){this.init.apply(this,arguments)};$b.prototype={Element:cb,init:function(a,b,c,d){var e=location,f;f=this.createElement("svg").attr({xmlns:"http://www.w3.org/2000/svg",version:"1.1"});a.appendChild(f.element);this.box=f.element;this.boxWrapper=f;this.alignedObjects=[];this.url=Rb?"":e.href.replace(/#.*?$/,"");this.defs=this.createElement("defs").add();this.forExport=d;this.gradients=[];this.setSize(b,c,!1)},destroy:function(){var a,b=this.gradients,
c=this.defs;this.box=null;this.boxWrapper=this.boxWrapper.destroy();if(b){for(a=0;a<b.length;a++)this.gradients[a]=b[a].destroy();this.gradients=null}if(c)this.defs=c.destroy();return this.alignedObjects=null},createElement:function(a){var b=new this.Element;b.init(this,a);return b},buildText:function(a){for(var b=a.element,c=p(a.textStr,"").toString().replace(/<(b|strong)>/g,'<span style="font-weight:bold">').replace(/<(i|em)>/g,'<span style="font-style:italic">').replace(/<a/g,"<span").replace(/<\/(b|strong|i|em|a)>/g,
"</span>").split(/<br.*?>/g),d=b.childNodes,e=/style="([^"]+)"/,f=/href="([^"]+)"/,g=P(b,"x"),h=a.styles,i=h&&a.useHTML&&!this.forExport,j=a.htmlNode,k=h&&M(h.width),n=h&&h.lineHeight,l,q=d.length;q--;)b.removeChild(d[q]);k&&!a.added&&this.box.appendChild(b);""===c[c.length-1]&&c.pop();o(c,function(c,d){var h,i=0,j,c=c.replace(/<span/g,"|||<span").replace(/<\/span>/g,"</span>|||");h=c.split("|||");o(h,function(c){if(""!==c||1===h.length){var o={},q=s.createElementNS("http://www.w3.org/2000/svg","tspan");
e.test(c)&&P(q,"style",c.match(e)[1].replace(/(;| |^)color([ :])/,"$1fill$2"));f.test(c)&&(P(q,"onclick",'location.href="'+c.match(f)[1]+'"'),y(q,{cursor:"pointer"}));c=(c.replace(/<(.|\n)*?>/g,"")||" ").replace(/&lt;/g,"<").replace(/&gt;/g,">");q.appendChild(s.createTextNode(c));i?o.dx=3:o.x=g;if(!i){if(d){!Qb&&a.renderer.forExport&&y(q,{display:"block"});j=wa.getComputedStyle&&M(wa.getComputedStyle(l,null).getPropertyValue("line-height"));if(!j||isNaN(j))j=n||l.offsetHeight||18;P(q,"dy",j)}l=q}P(q,
o);b.appendChild(q);i++;if(k)for(var c=c.replace(/-/g,"- ").split(" "),p,r=[];c.length||r.length;)p=a.getBBox().width,o=p>k,!o||1===c.length?(c=r,r=[],c.length&&(q=s.createElementNS("http://www.w3.org/2000/svg","tspan"),P(q,{dy:n||16,x:g}),b.appendChild(q),p>k&&(k=p))):(q.removeChild(q.firstChild),r.unshift(c.pop())),c.length&&q.appendChild(s.createTextNode(c.join(" ").replace(/- /g,"-")))}})});if(i){if(!j)j=a.htmlNode=aa("span",null,F(h,{position:nb,top:0,left:0}),this.box.parentNode);j.innerHTML=
a.textStr;for(q=d.length;q--;)d[q].style.visibility=Va}},button:function(a,b,c,d,e,f,g){var h=this.label(a,b,c),i=0,j,k,n,l,o,a={x1:0,y1:0,x2:0,y2:1},e=D(Ka("stroke-width",1,"stroke","#999","fill",Ka("linearGradient",a,"stops",[[0,"#FFF"],[1,"#DDD"]]),"r",3,"padding",3,"style",Ka("color","black")),e);n=e.style;delete e.style;f=D(e,Ka("stroke","#68A","fill",Ka("linearGradient",a,"stops",[[0,"#FFF"],[1,"#ACF"]])),f);l=f.style;delete f.style;g=D(e,Ka("stroke","#68A","fill",Ka("linearGradient",a,"stops",
[[0,"#9BD"],[1,"#CDF"]])),g);o=g.style;delete g.style;ca(h.element,"mouseenter",function(){h.attr(f).css(l)});ca(h.element,"mouseleave",function(){j=[e,f,g][i];k=[n,l,o][i];h.attr(j).css(k)});h.setState=function(a){(i=a)?2===a&&h.attr(g).css(o):h.attr(e).css(n)};return h.on("click",function(){d.call(h)}).attr(e).css(F({cursor:"default"},n))},crispLine:function(a,b){a[1]===a[4]&&(a[1]=a[4]=w(a[1])+b%2/2);a[2]===a[5]&&(a[2]=a[5]=w(a[2])+b%2/2);return a},path:function(a){return this.createElement("path").attr({d:a,
fill:ma})},circle:function(a,b,c){a=Aa(a)?a:{x:a,y:b,r:c};return this.createElement("circle").attr(a)},arc:function(a,b,c,d,e,f){if(Aa(a))b=a.y,c=a.r,d=a.innerR,e=a.start,f=a.end,a=a.x;return this.symbol("arc",a||0,b||0,c||0,c||0,{innerR:d||0,start:e||0,end:f||0})},rect:function(a,b,c,d,e,f){if(Aa(a))b=a.y,c=a.width,d=a.height,e=a.r,f=a.strokeWidth,a=a.x;e=this.createElement("rect").attr({rx:e,ry:e,fill:ma});return e.attr(e.crisp(f,a,b,W(c,0),W(d,0)))},setSize:function(a,b,c){var d=this.alignedObjects,
e=d.length;this.width=a;this.height=b;for(this.boxWrapper[p(c,!0)?"animate":"attr"]({width:a,height:b});e--;)d[e].align()},g:function(a){var b=this.createElement("g");return r(a)?b.attr({"class":ta+a}):b},image:function(a,b,c,d,e){var f={preserveAspectRatio:ma};1<arguments.length&&F(f,{x:b,y:c,width:d,height:e});f=this.createElement("image").attr(f);f.element.setAttributeNS?f.element.setAttributeNS("http://www.w3.org/1999/xlink","href",a):f.element.setAttribute("hc-svg-href",a);return f},symbol:function(a,
b,c,d,e,f){var g,h=this.symbols[a],h=h&&h(w(b),w(c),d,e,f),i=/^url\((.*?)\)$/,j;if(h)g=this.path(h),F(g,{symbolName:a,x:b,y:c,width:d,height:e}),f&&F(g,f);else if(i.test(a)){var k=function(a,b){a.attr({width:b[0],height:b[1]}).translate(-w(b[0]/2),-w(b[1]/2))};j=a.match(i)[1];a=Ec[j];g=this.image(j).attr({x:b,y:c});a?k(g,a):(g.attr({width:0,height:0}),aa("img",{onload:function(){k(g,Ec[j]=[this.width,this.height])},src:j}))}return g},symbols:{circle:function(a,b,c,d){var e=0.166*c;return[oa,a+c/2,
b,"C",a+c+e,b,a+c+e,b+d,a+c/2,b+d,"C",a-e,b+d,a-e,b,a+c/2,b,"Z"]},square:function(a,b,c,d){return[oa,a,b,ba,a+c,b,a+c,b+d,a,b+d,"Z"]},triangle:function(a,b,c,d){return[oa,a+c/2,b,ba,a+c,b+d,a,b+d,"Z"]},"triangle-down":function(a,b,c,d){return[oa,a,b,ba,a+c,b,a+c/2,b+d,"Z"]},diamond:function(a,b,c,d){return[oa,a+c/2,b,ba,a+c,b+d/2,a+c/2,b+d,a,b+d/2,"Z"]},arc:function(a,b,c,d,e){var f=e.start,c=e.r||c||d,g=e.end-1.0E-6,d=e.innerR,h=E(f),i=Z(f),j=E(g),g=Z(g),e=e.end-f<Ga?0:1;return[oa,a+c*h,b+c*i,"A",
c,c,0,e,1,a+c*j,b+c*g,ba,a+d*j,b+d*g,"A",d,d,0,e,0,a+d*h,b+d*i,"Z"]}},clipRect:function(a,b,c,d){var e=ta+lc++,f=this.createElement("clipPath").attr({id:e}).add(this.defs),a=this.rect(a,b,c,d,0).add(f);a.id=e;a.clipPath=f;return a},color:function(a,b,c){var d,e=/^rgba/;if(a&&a.linearGradient){var f=this,b=a.linearGradient,c=!b.length,g=ta+lc++,h,i,j;h=f.createElement("linearGradient").attr(F({id:g,x1:b.x1||b[0]||0,y1:b.y1||b[1]||0,x2:b.x2||b[2]||0,y2:b.y2||b[3]||0},c?null:{gradientUnits:"userSpaceOnUse"})).add(f.defs);
f.gradients.push(h);h.stops=[];o(a.stops,function(a){e.test(a[1])?(d=Ha(a[1]),i=d.get("rgb"),j=d.get("a")):(i=a[1],j=1);a=f.createElement("stop").attr({offset:a[0],"stop-color":i,"stop-opacity":j}).add(h);h.stops.push(a)});return"url("+this.url+"#"+g+")"}if(e.test(a))return d=Ha(a),P(b,c+"-opacity",d.get("a")),d.get("rgb");b.removeAttribute(c+"-opacity");return a},text:function(a,b,c,d){var e=Oa.chart.style,b=w(p(b,0)),c=w(p(c,0)),a=this.createElement("text").attr({x:b,y:c,text:a}).css({fontFamily:e.fontFamily,
fontSize:e.fontSize});a.x=b;a.y=c;a.useHTML=d;return a},label:function(a,b,c,d,e,f){function g(){var a=k.styles,a=a&&a.textAlign,b=z,c=z+w(1.2*M(k.element.style.fontSize||11));if(r(da)&&("center"===a||"right"===a))b+={center:0.5,right:1}[a]*(da-q.width);(b!==n.x||c!==n.y)&&n.attr({x:b,y:c});n.x=b;n.y=c}function h(a,b){l?l.attr(a,b):T[a]=b}function i(){k.attr({text:a,x:b,y:c,anchorX:e,anchorY:f})}var j=this,k=j.g(),n=j.text().attr({zIndex:1}).add(k),l,q,p="left",z=3,da,A,t,u,U=0,T={},s=k.attrSetters;
ca(k,"add",i);s.width=function(a){da=a;return!1};s.height=function(a){A=a;return!1};s.padding=function(a){z=a;g();return!1};s.align=function(a){p=a;return!1};s.text=function(a,b){n.attr(b,a);q=(void 0===da||void 0===A||k.styles.textAlign)&&n.getBBox(!0);k.width=(da||q.width)+2*z;k.height=(A||q.height)+2*z;if(!l)k.box=l=d?j.symbol(d,0,0,k.width,k.height):j.rect(0,0,k.width,k.height,0,T["stroke-width"]),l.add(k);l.attr(D({width:k.width,height:k.height},T));T=null;g();return!1};s["stroke-width"]=function(a,
b){U=a%2/2;h(b,a);return!1};s.stroke=s.fill=s.r=function(a,b){h(b,a);return!1};s.anchorX=function(a,b){e=a;h(b,a+U-t);return!1};s.anchorY=function(a,b){f=a;h(b,a-u);return!1};s.x=function(a){t=a;t-={left:0,center:0.5,right:1}[p]*((da||q.width)+z);k.attr("translateX",w(t));return!1};s.y=function(a){u=a;k.attr("translateY",w(a));return!1};var y=k.css;return F(k,{css:function(a){if(a){var b={},a=D({},a);o("fontSize,fontWeight,fontFamily,color,lineHeight,width".split(","),function(c){a[c]!==ha&&(b[c]=
a[c],delete a[c])});n.css(b)}return y.call(k,a)},getBBox:function(){return l.getBBox()},shadow:function(a){l.shadow(a);return k},destroy:function(){Ba(k,"add",i);Ba(k.element,"mouseenter");Ba(k.element,"mouseleave");n&&(n=n.destroy());cb.prototype.destroy.call(k)}})}};ac=$b;var pb;if(!Qb){var Qc=V(cb,{init:function(a,b){var c=["<",b,' filled="f" stroked="f"'],d=["position: ",nb,";"];("shape"===b||b===bb)&&d.push("left:0;top:0;width:10px;height:10px;");Sa&&d.push("visibility: ",b===bb?Va:ab);c.push(' style="',
d.join(""),'"/>');if(b)c=b===bb||"span"===b||"img"===b?c.join(""):a.prepVML(c),this.element=aa(c);this.renderer=a;this.attrSetters={}},add:function(a){var b=this.renderer,c=this.element,d=b.box,d=a?a.element||a:d;a&&a.inverted&&b.invertChild(c,d);Sa&&d.gVis===Va&&y(c,{visibility:Va});d.appendChild(c);this.added=!0;this.alignOnAdd&&!this.deferUpdateTransform&&this.updateTransform();X(this,"add");return this},toggleChildren:function(a,b){for(var c=a.childNodes,d=c.length;d--;)y(c[d],{visibility:b}),
"DIV"===c[d].nodeName&&this.toggleChildren(c[d],b)},attr:function(a,b){var c,d,e,f=this.element||{},g=f.style,h=f.nodeName,i=this.renderer,j=this.symbolName,k,n=this.shadows,l,o=this.attrSetters,p=this;jb(a)&&r(b)&&(c=a,a={},a[c]=b);if(jb(a))c=a,p="strokeWidth"===c||"stroke-width"===c?this.strokeweight:this[c];else for(c in a)if(d=a[c],l=!1,e=o[c]&&o[c](d,c),!1!==e){e!==ha&&(d=e);if(j&&/^(x|y|r|start|end|width|height|innerR|anchorX|anchorY)/.test(c))k||(this.symbolAttr(a),k=!0),l=!0;else if("d"===
c){d=d||[];this.d=d.join(" ");e=d.length;for(l=[];e--;)l[e]=kb(d[e])?w(10*d[e])-5:"Z"===d[e]?"x":d[e];d=l.join(" ")||"x";f.path=d;if(n)for(e=n.length;e--;)n[e].path=d;l=!0}else if("zIndex"===c||"visibility"===c){if(Sa&&"visibility"===c&&"DIV"===h)f.gVis=d,this.toggleChildren(f,d),d===ab&&(d=null);d&&(g[c]=d);l=!0}else if("width"===c||"height"===c)d=W(0,d),this[c]=d,this.updateClipping?(this[c]=d,this.updateClipping()):g[c]=d,l=!0;else if(/^(x|y)$/.test(c))this[c]=d,"SPAN"===f.tagName?this.updateTransform():
g[{x:"left",y:"top"}[c]]=d;else if("class"===c)f.className=d;else if("stroke"===c)d=i.color(d,f,c),c="strokecolor";else if("stroke-width"===c||"strokeWidth"===c)f.stroked=d?!0:!1,c="strokeweight",this[c]=d,kb(d)&&(d+=qa);else if("dashstyle"===c)(f.getElementsByTagName("stroke")[0]||aa(i.prepVML(["<stroke/>"]),null,null,f))[c]=d||"solid",this.dashstyle=d,l=!0;else if("fill"===c)"SPAN"===h?g.color=d:(f.filled=d!==ma?!0:!1,d=i.color(d,f,c),c="fillcolor");else if("translateX"===c||"translateY"===c||"rotation"===
c||"align"===c)"align"===c&&(c="textAlign"),this[c]=d,this.updateTransform(),l=!0;else if("text"===c)this.bBox=null,f.innerHTML=d,l=!0;if(n&&"visibility"===c)for(e=n.length;e--;)n[e].style[c]=d;l||(Sa?f[c]=d:P(f,c,d))}return p},clip:function(a){var b=this,c=a.members;c.push(b);b.destroyClip=function(){rb(c,b)};return b.css(a.getCSS(b.inverted))},css:function(a){var b=this.element;if(b=a&&"SPAN"===b.tagName&&a.width)delete a.width,this.textWidth=b,this.updateTransform();this.styles=F(this.styles,a);
y(this.element,a);return this},safeRemoveChild:function(a){a.parentNode&&vb(a)},destroy:function(){this.destroyClip&&this.destroyClip();return cb.prototype.destroy.apply(this)},empty:function(){for(var a=this.element.childNodes,b=a.length,c;b--;)c=a[b],c.parentNode.removeChild(c)},getBBox:function(a){var b=this.element,c=this.bBox;if(!c||a){if("text"===b.nodeName)b.style.position=nb;c=this.bBox={x:b.offsetLeft,y:b.offsetTop,width:b.offsetWidth,height:b.offsetHeight}}return c},on:function(a,b){this.element["on"+
a]=function(){var a=wa.event;a.target=a.srcElement;b(a)};return this},updateTransform:function(){if(this.added){var a=this,b=a.element,c=a.translateX||0,d=a.translateY||0,e=a.x||0,f=a.y||0,g=a.textAlign||"left",h={left:0,center:0.5,right:1}[g],i=g&&"left"!==g,j=a.shadows;if(c||d)y(b,{marginLeft:c,marginTop:d}),j&&o(j,function(a){y(a,{marginLeft:c+1,marginTop:d+1})});a.inverted&&o(b.childNodes,function(c){a.renderer.invertChild(c,b)});if("SPAN"===b.tagName){var k,n,j=a.rotation,l;k=0;var q=1,s=0,z;
l=M(a.textWidth);var da=a.xCorr||0;z=a.yCorr||0;var A=[j,g,b.innerHTML,a.textWidth].join();if(A!==a.cTT)r(j)&&(k=j*Dc,q=E(k),s=Z(k),y(b,{filter:j?["progid:DXImageTransform.Microsoft.Matrix(M11=",q,", M12=",-s,", M21=",s,", M22=",q,", sizingMethod='auto expand')"].join(""):ma})),k=p(a.elemWidth,b.offsetWidth),n=p(a.elemHeight,b.offsetHeight),k>l&&(y(b,{width:l+qa,display:"block",whiteSpace:"normal"}),k=l),l=w(1.2*(M(b.style.fontSize)||12)),z=0>q*s,da=(0>q&&-k)+s*l*(z?1-h:h),z=(0>s&&-n)-q*l*(j?z?h:
1-h:1),i&&(da-=k*h*(0>q?-1:1),j&&(z-=n*h*(0>s?-1:1)),y(b,{textAlign:g})),a.xCorr=da,a.yCorr=z;y(b,{left:e+da,top:f+z});a.cTT=A}}else this.alignOnAdd=!0},shadow:function(a,b){var c=[],d,e=this.element,f=this.renderer,g,h=e.style,i,j=e.path;j&&"string"!==typeof j.value&&(j="x");if(a){for(d=1;3>=d;d++)i=['<shape isShadow="true" strokeweight="',7-2*d,'" filled="false" path="',j,'" coordsize="100,100" style="',e.style.cssText,'" />'],g=aa(f.prepVML(i),null,{left:M(h.left)+1,top:M(h.top)+1}),i=['<stroke color="black" opacity="',
0.05*d,'"/>'],aa(f.prepVML(i),null,null,g),b?b.element.appendChild(g):e.parentNode.insertBefore(g,e),c.push(g);this.shadows=c}return this}});pb=function(){this.init.apply(this,arguments)};pb.prototype=D($b.prototype,{Element:Qc,isIE8:-1<gb.indexOf("MSIE 8.0"),init:function(a,b,c){var d;this.alignedObjects=[];d=this.createElement(bb);a.appendChild(d.element);this.box=d.element;this.boxWrapper=d;this.setSize(b,c,!1);if(!s.namespaces.hcv)s.namespaces.add("hcv","urn:schemas-microsoft-com:vml"),s.createStyleSheet().cssText=
"hcv\\:fill, hcv\\:path, hcv\\:shape, hcv\\:stroke{ behavior:url(#default#VML); display: inline-block; } "},clipRect:function(a,b,c,d){var e=this.createElement();return F(e,{members:[],left:a,top:b,width:c,height:d,getCSS:function(a){var b=this.top,c=this.left,d=c+this.width,e=b+this.height,b={clip:"rect("+w(a?c:b)+"px,"+w(a?e:d)+"px,"+w(a?d:e)+"px,"+w(a?b:c)+"px)"};!a&&Sa&&F(b,{width:d+qa,height:e+qa});return b},updateClipping:function(){o(e.members,function(a){a.css(e.getCSS(a.inverted))})}})},
color:function(a,b,c){var d,e=/^rgba/;if(a&&a.linearGradient){var f,g,h=a.linearGradient,i=h.x1||h[0]||0,j=h.y1||h[1]||0,k=h.x2||h[2]||0,h=h.y2||h[3]||0,n,l,p,r;o(a.stops,function(a,b){e.test(a[1])?(d=Ha(a[1]),f=d.get("rgb"),g=d.get("a")):(f=a[1],g=1);b?(p=f,r=g):(n=f,l=g)});a=90-180*ka.atan((h-j)/(k-i))/Ga;a=["<",c,' colors="0% ',n,",100% ",p,'" angle="',a,'" opacity="',r,'" o:opacity2="',l,'" type="gradient" focus="100%" method="any" />'];aa(this.prepVML(a),null,null,b)}else{if(e.test(a)&&"IMG"!==
b.tagName)return d=Ha(a),a=["<",c,' opacity="',d.get("a"),'"/>'],aa(this.prepVML(a),null,null,b),d.get("rgb");b=b.getElementsByTagName(c);if(b.length)b[0].opacity=1;return a}},prepVML:function(a){var b=this.isIE8,a=a.join("");b?(a=a.replace("/>",' xmlns="urn:schemas-microsoft-com:vml" />'),a=-1===a.indexOf('style="')?a.replace("/>",' style="display:inline-block;behavior:url(#default#VML);" />'):a.replace('style="','style="display:inline-block;behavior:url(#default#VML);')):a=a.replace("<","<hcv:");
return a},text:function(a,b,c){var d=Oa.chart.style;return this.createElement("span").attr({text:a,x:w(b),y:w(c)}).css({whiteSpace:"nowrap",fontFamily:d.fontFamily,fontSize:d.fontSize})},path:function(a){return this.createElement("shape").attr({coordsize:"100 100",d:a})},circle:function(a,b,c){return this.symbol("circle").attr({x:a,y:b,r:c})},g:function(a){var b;a&&(b={className:ta+a,"class":ta+a});return this.createElement(bb).attr(b)},image:function(a,b,c,d,e){var f=this.createElement("img").attr({src:a});
1<arguments.length&&f.css({left:b,top:c,width:d,height:e});return f},rect:function(a,b,c,d,e,f){if(Aa(a))b=a.y,c=a.width,d=a.height,f=a.strokeWidth,a=a.x;var g=this.symbol("rect");g.r=e;return g.attr(g.crisp(f,a,b,W(c,0),W(d,0)))},invertChild:function(a,b){var c=b.style;y(a,{flip:"x",left:M(c.width)-10,top:M(c.height)-10,rotation:-90})},symbols:{arc:function(a,b,c,d,e){var f=e.start,g=e.end,c=e.r||c||d,d=E(f),h=Z(f),i=E(g),j=Z(g),e=e.innerR,k=0.07/c,n=e&&0.1/e||0;if(0===g-f)return["x"];2*Ga-g+f<k?
i=-k:g-f<n&&(i=E(f+n));return["wa",a-c,b-c,a+c,b+c,a+c*d,b+c*h,a+c*i,b+c*j,"at",a-e,b-e,a+e,b+e,a+e*i,b+e*j,a+e*d,b+e*h,"x","e"]},circle:function(a,b,c,d){return["wa",a,b,a+c,b+d,a+c,b+d/2,a+c,b+d/2,"e"]},rect:function(a,b,c,d,e){if(!r(e))return[];var f=a+c,g=b+d,c=Ta(e.r||0,c,d);return[oa,a+c,b,ba,f-c,b,"wa",f-2*c,b,f,b+2*c,f-c,b,f,b+c,ba,f,g-c,"wa",f-2*c,g-2*c,f,g,f,g-c,f-c,g,ba,a+c,g,"wa",a,g-2*c,a+2*c,g,a+c,g,a,g-c,ba,a,b+c,"wa",a,b,a+2*c,b+2*c,a,b+c,a+c,b,"x","e"]}}});ac=pb}Vb.prototype.callbacks=
[];var Ia=function(){};Ia.prototype={init:function(a,b,c){var d=a.chart.counters;this.series=a;this.applyOptions(b,c);this.pointAttr={};if(a.options.colorByPoint){b=a.chart.options.colors;if(!this.options)this.options={};this.color=this.options.color=this.color||b[d.color++];d.wrapColor(b.length)}a.chart.pointCount++;return this},applyOptions:function(a,b){var c=this.series,d=typeof a;this.config=a;if("number"===d||null===a)this.y=a;else if("number"===typeof a[0])this.x=a[0],this.y=a[1];else if("object"===
d&&"number"!==typeof a.length)F(this,a),this.options=a;else if("string"===typeof a[0])this.name=a[0],this.y=a[1];if(this.x===ha)this.x=b===ha?c.autoIncrement():b},destroy:function(){var a=this.series,b=a.chart.hoverPoints,c;a.chart.pointCount--;b&&(this.setState(),rb(b,this));if(this===a.chart.hoverPoint)this.onMouseOut();a.chart.hoverPoints=null;if(this.graphic||this.dataLabel)Ba(this),this.destroyElements();this.legendItem&&this.series.chart.legend.destroyItem(this);for(c in this)this[c]=null},
destroyElements:function(){for(var a="graphic,tracker,dataLabel,group,connector,shadowGroup".split(","),b,c=6;c--;)b=a[c],this[b]&&(this[b]=this[b].destroy())},getLabelConfig:function(){return{x:this.category,y:this.y,key:this.name||this.category,series:this.series,point:this,percentage:this.percentage,total:this.total||this.stackTotal}},select:function(a,b){var c=this,d=c.series.chart,a=p(a,!c.selected);c.firePointEvent(a?"select":"unselect",{accumulate:b},function(){c.selected=a;c.setState(a&&"select");
b||o(d.getSelectedPoints(),function(a){if(a.selected&&a!==c)a.selected=!1,a.setState(ya),a.firePointEvent("unselect")})})},onMouseOver:function(){var a=this.series,b=a.chart,c=b.tooltip,d=b.hoverPoint;if(d&&d!==this)d.onMouseOut();this.firePointEvent("mouseOver");c&&(!c.shared||a.noSharedTooltip)&&c.refresh(this);this.setState(Qa);b.hoverPoint=this},onMouseOut:function(){this.firePointEvent("mouseOut");this.setState();this.series.chart.hoverPoint=null},tooltipFormatter:function(a){var b=this.series,
c=b.tooltipOptions,d=(""+this.y).split("."),d=d[1]?d[1].length:0,e=a.match(/\{(series|point)\.[a-zA-Z]+\}/g),f=/[\.}]/,g,h,i;for(i in e)h=e[i],jb(h)&&h!==a&&(g=1===h.indexOf("point")?this:b,g="{point.y}"===h?(c.yPrefix||"")+cc(this.y,p(c.yDecimals,d))+(c.ySuffix||""):g[e[i].split(f)[1]],a=a.replace(e[i],g));return a},update:function(a,b,c){var d=this,e=d.series,f=d.graphic,g,h=e.data,i=h.length,j=e.chart,b=p(b,!0);d.firePointEvent("update",{options:a},function(){d.applyOptions(a);Aa(a)&&(e.getAttribs(),
f&&f.attr(d.pointAttr[e.state]));for(g=0;g<i;g++)if(h[g]===d){e.xData[g]=d.x;e.yData[g]=d.y;e.options.data[g]=a;break}e.isDirty=!0;e.isDirtyData=!0;b&&j.redraw(c)})},remove:function(a,b){var c=this,d=c.series,e=d.chart,f,g=d.data,h=g.length;ub(b,e);a=p(a,!0);c.firePointEvent("remove",null,function(){for(f=0;f<h;f++)if(g[f]===c){g.splice(f,1);d.options.data.splice(f,1);d.xData.splice(f,1);d.yData.splice(f,1);break}c.destroy();d.isDirty=!0;d.isDirtyData=!0;a&&e.redraw()})},firePointEvent:function(a,
b,c){var d=this,e=this.series.options;(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])&&this.importEvents();"click"===a&&e.allowPointSelect&&(c=function(a){d.select(null,a.ctrlKey||a.metaKey||a.shiftKey)});X(this,a,b,c)},importEvents:function(){if(!this.hasImportedEvents){var a=D(this.series.options.point,this.options).events,b;this.events=a;for(b in a)ca(this,b,a[b]);this.hasImportedEvents=!0}},setState:function(a){var b=this.plotX,c=this.plotY,d=this.series,e=d.options.states,
f=Y[d.type].marker&&d.options.marker,g=f&&!f.enabled,h=f&&f.states[a],i=h&&!1===h.enabled,j=d.stateMarkerGraphic,k=d.chart,n=this.pointAttr,a=a||ya;if(!(a===this.state||this.selected&&"select"!==a||e[a]&&!1===e[a].enabled||a&&(i||g&&!h.enabled))){if(this.graphic)e=this.graphic.symbolName&&n[a].r,this.graphic.attr(D(n[a],e?{x:b-e,y:c-e,width:2*e,height:2*e}:{}));else{if(a){if(!j)e=f.radius,d.stateMarkerGraphic=j=k.renderer.symbol(d.symbol,-e,-e,2*e,2*e).attr(n[a]).add(d.group);j.translate(b,c)}if(j)j[a?
"show":"hide"]()}this.state=a}}};var N=function(){};N.prototype={isCartesian:!0,type:"line",pointClass:Ia,pointAttrToOptions:{stroke:"lineColor","stroke-width":"lineWidth",fill:"fillColor",r:"radius"},init:function(a,b){var c,d;d=a.series.length;this.chart=a;this.options=b=this.setOptions(b);this.bindAxes();F(this,{index:d,name:b.name||"Series "+(d+1),state:ya,pointAttr:{},visible:!1!==b.visible,selected:!0===b.selected});d=b.events;for(c in d)ca(this,c,d[c]);if(d&&d.click||b.point&&b.point.events&&
b.point.events.click||b.allowPointSelect)a.runTrackerClick=!0;this.getColor();this.getSymbol();this.setData(b.data,!1)},bindAxes:function(){var a=this,b=a.options,c=a.chart,d;a.isCartesian&&o(["xAxis","yAxis"],function(e){o(c[e],function(c){d=c.options;if(b[e]===d.index||b[e]===ha&&0===d.index)c.series.push(a),a[e]=c,c.isDirty=!0})})},autoIncrement:function(){var a=this.options,b=this.xIncrement,b=p(b,a.pointStart,0);this.pointInterval=p(this.pointInterval,a.pointInterval,1);this.xIncrement=b+this.pointInterval;
return b},getSegments:function(){var a=-1,b=[],c,d=this.points,e=d.length;if(e)if(this.options.connectNulls){for(c=e;c--;)null===d[c].y&&d.splice(c,1);b=[d]}else o(d,function(c,g){null===c.y?(g>a+1&&b.push(d.slice(a+1,g)),a=g):g===e-1&&b.push(d.slice(a+1,g+1))});this.segments=b},setOptions:function(a){var b=this.chart.options,c=b.plotOptions,d=a.data;a.data=null;a=D(c[this.type],c.series,a);a.data=d;this.tooltipOptions=D(b.tooltip,a.tooltip);return a},getColor:function(){var a=this.chart.options.colors,
b=this.chart.counters;this.color=this.options.color||a[b.color++]||"#0000ff";b.wrapColor(a.length)},getSymbol:function(){var a=this.options.marker,b=this.chart,c=b.options.symbols,b=b.counters;this.symbol=a.symbol||c[b.symbol++];if(/^url/.test(this.symbol))a.radius=0;b.wrapSymbol(c.length)},addPoint:function(a,b,c,d){var e=this.data,f=this.graph,g=this.area,h=this.chart,i=this.xData,j=this.yData,k=f&&f.shift||0,n=this.options.data;ub(d,h);if(f&&c)f.shift=k+1;if(g)g.shift=k+1,g.isArea=!0;b=p(b,!0);
d={series:this};this.pointClass.prototype.applyOptions.apply(d,[a]);i.push(d.x);j.push(4===this.valueCount?[d.open,d.high,d.low,d.close]:d.y);n.push(a);c&&(e[0]?e[0].remove(!1):(e.shift(),i.shift(),j.shift(),n.shift()));this.getAttribs();this.isDirtyData=this.isDirty=!0;b&&h.redraw()},setData:function(a,b){var c=this.points,d=this.options,e=this.initialColor,f=this.chart,g=null;this.xIncrement=null;this.pointRange=this.xAxis&&this.xAxis.categories&&1||d.pointRange;if(r(e))f.counters.color=e;var h=
[],i=[],j=a?a.length:[],k=4===this.valueCount;if(j>(d.turboThreshold||1E3)){for(e=0;null===g&&e<j;)g=a[e],e++;if(kb(g)){g=p(d.pointStart,0);d=p(d.pointInterval,1);for(e=0;e<j;e++)h[e]=g,i[e]=a[e],g+=d;this.xIncrement=g}else if("[object Array]"===Object.prototype.toString.call(g))if(k)for(e=0;e<j;e++)d=a[e],h[e]=d[0],i[e]=d.slice(1,5);else for(e=0;e<j;e++)d=a[e],h[e]=d[0],i[e]=d[1]}else for(e=0;e<j;e++)d={series:this},this.pointClass.prototype.applyOptions.apply(d,[a[e]]),h[e]=d.x,i[e]=k?[d.open,d.high,
d.low,d.close]:d.y;this.data=[];this.options.data=a;this.xData=h;this.yData=i;for(e=c&&c.length||0;e--;)c[e]&&c[e].destroy&&c[e].destroy();this.isDirty=this.isDirtyData=f.isDirtyBox=!0;p(b,!0)&&f.redraw(!1)},remove:function(a,b){var c=this,d=c.chart,a=p(a,!0);if(!c.isRemoving)c.isRemoving=!0,X(c,"remove",null,function(){c.destroy();d.isDirtyLegend=d.isDirtyBox=!0;a&&d.redraw(b)});c.isRemoving=!1},processData:function(){var a=this.xData,b=this.yData,c=a.length,d=0,e=c,f,g,h,i=this.options;h=i.cropThreshold;
if(this.isCartesian&&!this.isDirty&&!this.xAxis.isDirty&&!this.yAxis.isDirty)return!1;if(!h||c>h||this.forceCrop){h=this.xAxis.getExtremes();var j=h.min,k=h.max;if(a[c-1]<j||a[0]>k)a=[],b=[];else if(a[0]<j||a[c-1]>k){for(h=0;h<c;h++)if(a[h]>=j){d=W(0,h-1);break}for(;h<c;h++)if(a[h]>k){e=h+1;break}a=a.slice(d,e);b=b.slice(d,e);f=!0}}for(h=a.length-1;0<h;h--)if(c=a[h]-a[h-1],g===ha||c<g)g=c;this.cropped=f;this.cropStart=d;this.processedXData=a;this.processedYData=b;if(null===i.pointRange)this.pointRange=
g||1;this.closestPointRange=g},generatePoints:function(){var a=this.options.data,b=this.data,c,d=this.processedXData,e=this.processedYData,f=this.pointClass,g=d.length,h=this.cropStart||0,i,j=this.hasGroupedData,k,n=[],l;if(!b&&!j)b=[],b.length=a.length,b=this.data=b;for(l=0;l<g;l++)i=h+l,j?n[l]=(new f).init(this,[d[l]].concat(sb(e[l]))):(b[i]?k=b[i]:b[i]=k=(new f).init(this,a[i],d[l]),n[l]=k);if(b&&(g!==(c=b.length)||j))for(l=0;l<c;l++)l===h&&!j&&(l+=g),b[l]&&b[l].destroyElements();this.data=b;this.points=
n},translate:function(){this.processedXData||this.processData();this.generatePoints();var a=this.chart,b=this.options,c=b.stacking,d=this.xAxis.categories,e=this.yAxis,f=this.points,g=f.length,h=!!this.modifyValue,i=this.index===this.yAxis.series.length-1,j;for(j=0;j<g;j++){var k=f[j],n=k.x,l=k.y,o=k.low,p=e.stacks[(l<b.threshold?"-":"")+this.stackKey];k.plotX=w(10*this.xAxis.translate(n))/10;if(c&&this.visible&&p&&p[n]){o=p[n];n=o.total;o.cum=o=o.cum-l;l=o+l;if(i)o=b.threshold;"percent"===c&&(o=
n?100*o/n:0,l=n?100*l/n:0);k.percentage=n?100*k.y/n:0;k.stackTotal=n}if(r(o))k.yBottom=e.translate(o,0,1,0,1);h&&(l=this.modifyValue(l,k));if(null!==l)k.plotY=w(10*e.translate(l,0,1,0,1))/10;k.clientX=a.inverted?a.plotHeight-k.plotX:k.plotX;k.category=d&&d[k.x]!==ha?d[k.x]:k.x}this.getSegments()},setTooltipPoints:function(a){var b=this.chart,c=b.inverted,d=[],b=w((c?b.plotTop:b.plotLeft)+b.plotSizeX),e,f;e=this.xAxis;var g,h,i=[];if(!1!==this.options.enableMouseTracking){if(a)this.tooltipPoints=null;
o(this.segments||this.points,function(a){d=d.concat(a)});e&&e.reversed&&(d=d.reverse());a=d.length;for(h=0;h<a;h++){g=d[h];e=d[h-1]?d[h-1]._high+1:0;for(f=g._high=d[h+1]?Ua((g.plotX+(d[h+1]?d[h+1].plotX:b))/2):b;e<=f;)i[c?b-e++:e++]=g}this.tooltipPoints=i}},tooltipHeaderFormatter:function(a){var b=this.tooltipOptions,c=b.xDateFormat||"%A, %b %e, %Y",d=this.xAxis;return b.headerFormat.replace("{point.key}",d&&"datetime"===d.options.type?Zb(c,a):a).replace("{series.name}",this.name).replace("{series.color}",
this.color)},onMouseOver:function(){var a=this.chart,b=a.hoverSeries;if(Ma||!a.mouseIsDown){if(b&&b!==this)b.onMouseOut();this.options.events.mouseOver&&X(this,"mouseOver");this.setState(Qa);a.hoverSeries=this}},onMouseOut:function(){var a=this.options,b=this.chart,c=b.tooltip,d=b.hoverPoint;if(d)d.onMouseOut();this&&a.events.mouseOut&&X(this,"mouseOut");c&&!a.stickyTracking&&!c.shared&&c.hide();this.setState();b.hoverSeries=null},animate:function(a){var b=this.chart,c=this.clipRect,d=this.options.animation;
d&&!Aa(d)&&(d={});if(a){if(!c.isAnimating)c.attr("width",0),c.isAnimating=!0}else c.animate({width:b.plotSizeX},d),this.animate=null},drawPoints:function(){var a,b=this.points,c=this.chart,d,e,f,g,h,i;if(this.options.marker.enabled)for(f=b.length;f--;)if(g=b[f],d=g.plotX,e=g.plotY,i=g.graphic,e!==ha&&!isNaN(e))if(a=g.pointAttr[g.selected?"select":ya],h=a.r,i)i.animate(F({x:d-h,y:e-h},i.symbolName?{width:2*h,height:2*h}:{}));else if(0<h)g.graphic=c.renderer.symbol(p(g.marker&&g.marker.symbol,this.symbol),
d-h,e-h,2*h,2*h).attr(a).add(this.group)},convertAttribs:function(a,b,c,d){var e=this.pointAttrToOptions,f,g,h={},a=a||{},b=b||{},c=c||{},d=d||{};for(f in e)g=e[f],h[f]=p(a[g],b[f],c[f],d[f]);return h},getAttribs:function(){var a=this,b=Y[a.type].marker?a.options.marker:a.options,c=b.states,d=c[Qa],e,f=a.color,g={stroke:f,fill:f},h=a.points,i=[],j,k=a.pointAttrToOptions,n;a.options.marker?(d.radius=d.radius||b.radius+2,d.lineWidth=d.lineWidth||b.lineWidth+1):d.color=d.color||Ha(d.color||f).brighten(d.brightness).get();
i[ya]=a.convertAttribs(b,g);o([Qa,"select"],function(b){i[b]=a.convertAttribs(c[b],i[ya])});a.pointAttr=i;for(f=h.length;f--;){g=h[f];if((b=g.options&&g.options.marker||g.options)&&!1===b.enabled)b.radius=0;e=!1;if(g.options)for(n in k)r(b[k[n]])&&(e=!0);if(e){j=[];c=b.states||{};e=c[Qa]=c[Qa]||{};if(!a.options.marker)e.color=Ha(e.color||g.options.color).brighten(e.brightness||d.brightness).get();j[ya]=a.convertAttribs(b,i[ya]);j[Qa]=a.convertAttribs(c[Qa],i[Qa],j[ya]);j.select=a.convertAttribs(c.select,
i.select,j[ya])}else j=i;g.pointAttr=j}},destroy:function(){var a=this,b=a.chart,c=a.clipRect,d=/AppleWebKit\/533/.test(gb),e,f,g=a.data||[],h,i,j;X(a,"destroy");Ba(a);o(["xAxis","yAxis"],function(b){if(j=a[b])rb(j.series,a),j.isDirty=!0});a.legendItem&&a.chart.legend.destroyItem(a);for(f=g.length;f--;)(h=g[f])&&h.destroy&&h.destroy();a.points=null;if(c&&c!==b.clipRect)a.clipRect=c.destroy();o(["area","graph","dataLabelsGroup","group","tracker"],function(b){a[b]&&(e=d&&"group"===b?"hide":"destroy",
a[b][e]())});if(b.hoverSeries===a)b.hoverSeries=null;rb(b.series,a);for(i in a)delete a[i]},drawDataLabels:function(){if(this.options.dataLabels.enabled){var a,b,c=this.points,d=this.options,e=d.dataLabels,f,g=this.dataLabelsGroup,h=this.chart,i=this.xAxis,i=i?i.left:h.plotLeft,j=this.yAxis,j=j?j.top:h.plotTop,k=h.renderer,n=h.inverted,l=this.type,q=d.stacking,s="column"===l||"bar"===l,z=null===e.verticalAlign,w=null===e.y;s&&(q?(z&&(e=D(e,{verticalAlign:"middle"})),w&&(e=D(e,{y:{top:14,middle:4,
bottom:-6}[e.verticalAlign]}))):z&&(e=D(e,{verticalAlign:"top"})));g?g.translate(i,j):g=this.dataLabelsGroup=k.g("data-labels").attr({visibility:this.visible?ab:Va,zIndex:6}).translate(i,j).add();i=e.color;"auto"===i&&(i=null);e.style.color=p(i,this.color,"black");o(c,function(c){var i=c.barX,j=i&&i+c.barW/2||c.plotX||-999,o=p(c.plotY,-999),q=c.dataLabel,z=e.align,y=w?0<=c.y?-6:12:e.y;f=e.formatter.call(c.getLabelConfig());a=(n?h.plotWidth-o:j)+e.x;b=(n?h.plotHeight-j:o)+y;"column"===l&&(a+={left:-1,
right:1}[z]*c.barW/2||0);n&&0>c.y&&(z="right",a-=10);if(q)n&&!e.y&&(b=b+0.9*M(q.styles.lineHeight)-q.getBBox().height/2),q.attr({text:f}).animate({x:a,y:b});else if(r(f))q=c.dataLabel=k.text(f,a,b).attr({align:z,rotation:e.rotation,zIndex:1}).css(e.style).add(g),n&&!e.y&&q.attr({y:b+0.9*M(q.styles.lineHeight)-q.getBBox().height/2});if(s&&d.stacking&&q)j=c.barY,o=c.barW,c=c.barH,q.align(e,null,{x:n?h.plotWidth-j-c:i,y:n?h.plotHeight-i-o:j,width:n?c:o,height:n?o:c})})}},drawGraph:function(){var a=this,
b=a.options,c=a.graph,d=[],e,f=a.area,g=a.group,h=b.lineColor||a.color,i=b.lineWidth,j=b.dashStyle,k,n=a.chart.renderer,l=a.yAxis.getThreshold(b.threshold),q=/^area/.test(a.type),r=[],z=[];o(a.segments,function(c){k=[];o(c,function(d,e){a.getPointSpline?k.push.apply(k,a.getPointSpline(c,d,e)):(k.push(e?ba:oa),e&&b.step&&k.push(d.plotX,c[e-1].plotY),k.push(d.plotX,d.plotY))});1<c.length?d=d.concat(k):r.push(c[0]);if(q){var e=[],f,g=k.length;for(f=0;f<g;f++)e.push(k[f]);3===g&&e.push(ba,k[1],k[2]);
if(b.stacking&&"areaspline"!==a.type)for(f=c.length-1;0<=f;f--)f<c.length-1&&b.step&&e.push(c[f+1].plotX,c[f].yBottom),e.push(c[f].plotX,c[f].yBottom);else e.push(ba,c[c.length-1].plotX,l,ba,c[0].plotX,l);z=z.concat(e)}});a.graphPath=d;a.singlePoints=r;if(q)e=p(b.fillColor,Ha(a.color).setOpacity(b.fillOpacity||0.75).get()),f?f.animate({d:z}):a.area=a.chart.renderer.path(z).attr({fill:e}).add(g);if(c)Cb(c),c.animate({d:d});else if(i){c={stroke:h,"stroke-width":i};if(j)c.dashstyle=j;a.graph=n.path(d).attr(c).add(g).shadow(b.shadow)}},
render:function(){var a=this,b=a.chart,c,d,e=a.options,f=!1!==e.clip,g=e.animation,h=g&&a.animate,g=h?g&&g.duration||500:0,i=a.clipRect,j=b.renderer;if(!i&&(i=a.clipRect=!b.hasRendered&&b.clipRect?b.clipRect:j.clipRect(0,0,b.plotSizeX,b.plotSizeY+1),!b.clipRect))b.clipRect=i;if(!a.group)c=a.group=j.g("series"),b.inverted&&(d=function(){c.attr({width:b.plotWidth,height:b.plotHeight}).invert()},d(),ca(b,"resize",d),ca(a,"destroy",function(){Ba(b,"resize",d)})),f&&c.clip(a.clipRect),c.attr({visibility:a.visible?
ab:Va,zIndex:e.zIndex}).translate(a.xAxis.left,a.yAxis.top).add(b.seriesGroup);a.drawDataLabels();h&&a.animate(!0);a.getAttribs();a.drawGraph&&a.drawGraph();a.drawPoints();!1!==a.options.enableMouseTracking&&a.drawTracker();h&&a.animate();setTimeout(function(){i.isAnimating=!1;if((c=a.group)&&i!==b.clipRect&&i.renderer){if(f)c.clip(a.clipRect=b.clipRect);i.destroy()}},g);a.isDirty=a.isDirtyData=!1},redraw:function(){var a=this.chart,b=this.isDirtyData,c=this.group;c&&(a.inverted&&c.attr({width:a.plotWidth,
height:a.plotHeight}),c.animate({translateX:this.xAxis.left,translateY:this.yAxis.top}));this.translate();this.setTooltipPoints(!0);this.render();b&&X(this,"updatedData")},setState:function(a){var b=this.options,c=this.graph,d=b.states,b=b.lineWidth,a=a||ya;if(this.state!==a)this.state=a,d[a]&&!1===d[a].enabled||(a&&(b=d[a].lineWidth||b+1),c&&!c.dashstyle&&c.attr({"stroke-width":b},a?0:500))},setVisible:function(a,b){var c=this.chart,d=this.legendItem,e=this.group,f=this.tracker,g=this.dataLabelsGroup,
h,i=this.points,j=c.options.chart.ignoreHiddenSeries;h=this.visible;h=(this.visible=a=a===ha?!h:a)?"show":"hide";if(e)e[h]();if(f)f[h]();else if(i)for(e=i.length;e--;)if(f=i[e],f.tracker)f.tracker[h]();if(g)g[h]();d&&c.legend.colorizeItem(this,a);this.isDirty=!0;this.options.stacking&&o(c.series,function(a){if(a.options.stacking&&a.visible)a.isDirty=!0});if(j)c.isDirtyBox=!0;!1!==b&&c.redraw();X(this,h)},show:function(){this.setVisible(!0)},hide:function(){this.setVisible(!1)},select:function(a){this.selected=
a=a===ha?!this.selected:a;if(this.checkbox)this.checkbox.checked=a;X(this,a?"select":"unselect")},drawTracker:function(){var a=this,b=a.options,c=[].concat(a.graphPath),d=c.length,e=a.chart,f=e.options.tooltip.snap,g=a.tracker,h=b.cursor,h=h&&{cursor:h},i=a.singlePoints,j;if(d)for(j=d+1;j--;)c[j]===oa&&c.splice(j+1,0,c[j+1]-f,c[j+2],ba),(j&&c[j]===oa||j===d)&&c.splice(j,0,ba,c[j-2]+f,c[j-1]);for(j=0;j<i.length;j++)d=i[j],c.push(oa,d.plotX-f,d.plotY,ba,d.plotX+f,d.plotY);g?g.attr({d:c}):a.tracker=
e.renderer.path(c).attr({isTracker:!0,stroke:Fc,fill:ma,"stroke-width":b.lineWidth+2*f,visibility:a.visible?ab:Va,zIndex:b.zIndex||1}).on(Ma?"touchstart":"mouseover",function(){if(e.hoverSeries!==a)a.onMouseOver()}).on("mouseout",function(){if(!b.stickyTracking)a.onMouseOut()}).css(h).add(e.trackerGroup)}};var Rc=V(N);ga.line=Rc;var Sc=V(N,{type:"area",useThreshold:!0});ga.area=Sc;var Ic=V(N,{type:"spline",getPointSpline:function(a,b,c){var d=b.plotX,e=b.plotY,f=a[c-1],g=a[c+1],h,i,j,k;if(c&&c<a.length-
1){a=f.plotY;j=g.plotX;var g=g.plotY,n;h=(1.5*d+f.plotX)/2.5;i=(1.5*e+a)/2.5;j=(1.5*d+j)/2.5;k=(1.5*e+g)/2.5;n=(k-i)*(j-d)/(j-h)+e-k;i+=n;k+=n;i>a&&i>e?(i=W(a,e),k=2*e-i):i<a&&i<e&&(i=Ta(a,e),k=2*e-i);k>g&&k>e?(k=W(g,e),i=2*e-k):k<g&&k<e&&(k=Ta(g,e),i=2*e-k);b.rightContX=j;b.rightContY=k}c?(b=["C",f.rightContX||f.plotX,f.rightContY||f.plotY,h||d,i||e,d,e],f.rightContX=f.rightContY=null):b=[oa,d,e];return b}});ga.spline=Ic;var Tc=V(Ic,{type:"areaspline",useThreshold:!0});ga.areaspline=Tc;var Ja=V(N,
{type:"column",useThreshold:!0,pointAttrToOptions:{stroke:"borderColor","stroke-width":"borderWidth",fill:"color",r:"borderRadius"},init:function(){N.prototype.init.apply(this,arguments);var a=this,b=a.chart;b.hasRendered&&o(b.series,function(b){if(b.type===a.type)b.isDirty=!0})},translate:function(){var a=this,b=a.chart,c=a.options,d=c.stacking,e=c.borderWidth,f=0,g=a.xAxis,h=g.reversed,i={},j,k;N.prototype.translate.apply(a);o(b.series,function(b){if(b.type===a.type&&b.visible&&a.options.group===
b.options.group)b.options.stacking?(j=b.stackKey,i[j]===ha&&(i[j]=f++),k=i[j]):k=f++,b.columnIndex=k});var n=a.points,g=va(g.translationSlope)*(g.ordinalSlope||g.closestPointRange),l=g*c.groupPadding,q=(g-2*l)/f,s=c.pointWidth,z=r(s)?(q-s)/2:q*c.pointPadding,w=Xb(W(p(s,q-2*z),1)),A=z+(l+((h?f-a.columnIndex:a.columnIndex)||0)*q-g/2)*(h?-1:1),t=a.yAxis.getThreshold(c.threshold),u=p(c.minPointLength,5);o(n,function(f){var g=f.plotY,h=f.yBottom||t,i=f.plotX+A,j=Xb(Ta(g,h)),k=Xb(W(g,h)-j),l=a.yAxis.stacks[(0>
f.y?"-":"")+a.stackKey],n;d&&a.visible&&l&&l[f.x]&&l[f.x].setOffset(A,w);va(k)<u&&(u&&(k=u,j=va(j-t)>u?h-u:t-(g<=t?u:0)),n=j-3);F(f,{barX:i,barY:j,barW:w,barH:k});f.shapeType="rect";g=F(b.renderer.Element.prototype.crisp.apply({},[e,i,j,w,k]),{r:c.borderRadius});e%2&&(g.y-=1,g.height+=1);f.shapeArgs=g;f.trackerArgs=r(n)&&D(f.shapeArgs,{height:W(6,k+3),y:n})})},getSymbol:function(){},drawGraph:function(){},drawPoints:function(){var a=this,b=a.options,c=a.chart.renderer,d,e;o(a.points,function(f){var g=
f.plotY;if(g!==ha&&!isNaN(g)&&null!==f.y)d=f.graphic,e=f.shapeArgs,d?(Cb(d),d.animate(e)):f.graphic=d=c[f.shapeType](e).attr(f.pointAttr[f.selected?"select":ya]).add(a.group).shadow(b.shadow)})},drawTracker:function(){var a=this,b=a.chart,c=b.renderer,d,e,f=+new Date,g=a.options,h=g.cursor,i=h&&{cursor:h},j;o(a.points,function(h){e=h.tracker;d=h.trackerArgs||h.shapeArgs;delete d.strokeWidth;if(null!==h.y)e?e.attr(d):h.tracker=c[h.shapeType](d).attr({isTracker:f,fill:Fc,visibility:a.visible?ab:Va,
zIndex:g.zIndex||1}).on(Ma?"touchstart":"mouseover",function(c){j=c.relatedTarget||c.fromElement;if(b.hoverSeries!==a&&P(j,"isTracker")!==f)a.onMouseOver();h.onMouseOver()}).on("mouseout",function(b){if(!g.stickyTracking&&(j=b.relatedTarget||b.toElement,P(j,"isTracker")!==f))a.onMouseOut()}).css(i).add(h.group||b.trackerGroup)})},animate:function(a){var b=this,c=b.points;if(!a)o(c,function(a){var c=a.graphic,a=a.shapeArgs;c&&(c.attr({height:0,y:b.yAxis.translate(0,0,1)}),c.animate({height:a.height,
y:a.y},b.options.animation))}),b.animate=null},remove:function(){var a=this,b=a.chart;b.hasRendered&&o(b.series,function(b){if(b.type===a.type)b.isDirty=!0});N.prototype.remove.apply(a,arguments)}});ga.column=Ja;var Uc=V(Ja,{type:"bar",init:function(){this.inverted=!0;Ja.prototype.init.apply(this,arguments)}});ga.bar=Uc;var Vc=V(N,{type:"scatter",translate:function(){var a=this;N.prototype.translate.apply(a);o(a.points,function(b){b.shapeType="circle";b.shapeArgs={x:b.plotX,y:b.plotY,r:a.chart.options.tooltip.snap}})},
drawTracker:function(){var a=this,b=a.options.cursor,c=b&&{cursor:b},d;o(a.points,function(b){(d=b.graphic)&&d.attr({isTracker:!0}).on("mouseover",function(){a.onMouseOver();b.onMouseOver()}).on("mouseout",function(){if(!a.options.stickyTracking)a.onMouseOut()}).css(c)})}});ga.scatter=Vc;var Wc=V(Ia,{init:function(){Ia.prototype.init.apply(this,arguments);var a=this,b;F(a,{visible:!1!==a.visible,name:p(a.name,"Slice")});b=function(){a.slice()};ca(a,"select",b);ca(a,"unselect",b);return a},setVisible:function(a){var b=
this.series.chart,c=this.tracker,d=this.dataLabel,e=this.connector,f=this.shadowGroup,g;g=(this.visible=a=a===ha?!this.visible:a)?"show":"hide";this.group[g]();if(c)c[g]();if(d)d[g]();if(e)e[g]();if(f)f[g]();this.legendItem&&b.legend.colorizeItem(this,a)},slice:function(a,b,c){var d=this.series.chart,e=this.slicedTranslation;ub(c,d);p(b,!0);a=this.sliced=r(a)?a:!this.sliced;a={translateX:a?e[0]:d.plotLeft,translateY:a?e[1]:d.plotTop};this.group.animate(a);this.shadowGroup&&this.shadowGroup.animate(a)}}),
Xc=V(N,{type:"pie",isCartesian:!1,pointClass:Wc,pointAttrToOptions:{stroke:"borderColor","stroke-width":"borderWidth",fill:"color"},getColor:function(){this.initialColor=this.chart.counters.color},animate:function(){var a=this;o(a.points,function(b){var c=b.graphic,b=b.shapeArgs,d=-Ga/2;c&&(c.attr({r:0,start:d,end:d}),c.animate({r:b.r,start:b.start,end:b.end},a.options.animation))});a.animate=null},setData:function(){N.prototype.setData.apply(this,arguments);this.processData();this.generatePoints()},
translate:function(){this.generatePoints();var a=0,b=-0.25,c=this.options,d=c.slicedOffset,e=d+c.borderWidth,f=c.center.concat([c.size,c.innerSize||0]),g=this.chart,h=g.plotWidth,i=g.plotHeight,j,k,n,l=this.points,p=2*Ga,r,s=Ta(h,i),y,A,t,u=c.dataLabels.distance,f=ua(f,function(a,b){return(y=/%$/.test(a))?[h,i,s,s][b]*M(a)/100:a});this.getX=function(a,b){n=ka.asin((a-f[1])/(f[2]/2+u));return f[0]+(b?-1:1)*E(n)*(f[2]/2+u)};this.center=f;o(l,function(b){a+=b.y});o(l,function(c){r=a?c.y/a:0;j=w(1E3*
b*p)/1E3;b+=r;k=w(1E3*b*p)/1E3;c.shapeType="arc";c.shapeArgs={x:f[0],y:f[1],r:f[2]/2,innerR:f[3]/2,start:j,end:k};n=(k+j)/2;c.slicedTranslation=ua([E(n)*d+g.plotLeft,Z(n)*d+g.plotTop],w);A=E(n)*f[2]/2;t=Z(n)*f[2]/2;c.tooltipPos=[f[0]+0.7*A,f[1]+0.7*t];c.labelPos=[f[0]+A+E(n)*u,f[1]+t+Z(n)*u,f[0]+A+E(n)*e,f[1]+t+Z(n)*e,f[0]+A,f[1]+t,0>u?"center":n<p/4?"left":"right",n];c.percentage=100*r;c.total=a});this.setTooltipPoints()},render:function(){this.getAttribs();this.drawPoints();!1!==this.options.enableMouseTracking&&
this.drawTracker();this.drawDataLabels();this.options.animation&&this.animate&&this.animate();this.isDirty=!1},drawPoints:function(){var a=this.chart,b=a.renderer,c,d,e,f=this.options.shadow,g,h;o(this.points,function(i){d=i.graphic;h=i.shapeArgs;e=i.group;g=i.shadowGroup;if(f&&!g)g=i.shadowGroup=b.g("shadow").attr({zIndex:4}).add();if(!e)e=i.group=b.g("point").attr({zIndex:5}).add();c=i.sliced?i.slicedTranslation:[a.plotLeft,a.plotTop];e.translate(c[0],c[1]);g&&g.translate(c[0],c[1]);d?d.animate(h):
i.graphic=b.arc(h).attr(F(i.pointAttr[ya],{"stroke-linejoin":"round"})).add(i.group).shadow(f,g);!1===i.visible&&i.setVisible(!1)})},drawDataLabels:function(){var a=this.data,b,c=this.chart,d=this.options.dataLabels,e=p(d.connectorPadding,10),f=p(d.connectorWidth,1),g,h,i=p(d.softConnector,!0),j=d.distance,k=this.center,n=k[2]/2,k=k[1],l=0<j,q=[[],[]],r,s,w,A,t=2,u;if(d.enabled){N.prototype.drawDataLabels.apply(this);o(a,function(a){a.dataLabel&&q[a.labelPos[7]<Ga/2?0:1].push(a)});q[1].reverse();
A=function(a,b){return b.y-a.y};for(a=q[0][0]&&q[0][0].dataLabel&&M(q[0][0].dataLabel.styles.lineHeight);t--;){var y=[],F=[],E=q[t],D=E.length,C;for(u=k-n-j;u<=k+n+j;u+=a)y.push(u);w=y.length;if(D>w){h=[].concat(E);h.sort(A);for(u=D;u--;)h[u].rank=u;for(u=D;u--;)E[u].rank>=w&&E.splice(u,1);D=E.length}for(u=0;u<D;u++){b=E[u];h=b.labelPos;b=9999;for(s=0;s<w;s++)g=va(y[s]-h[1]),g<b&&(b=g,C=s);if(C<u&&null!==y[u])C=u;else for(w<D-u+C&&null!==y[u]&&(C=w-D+u);null===y[C];)C++;F.push({i:C,y:y[C]});y[C]=
null}F.sort(A);for(u=0;u<D;u++){b=E[u];h=b.labelPos;g=b.dataLabel;s=F.pop();r=h[1];w=!1===b.visible?Va:ab;C=s.i;s=s.y;if(r>s&&null!==y[C+1]||r<s&&null!==y[C-1])s=r;r=this.getX(0===C||C===y.length-1?r:s,t);g.attr({visibility:w,align:h[6]})[g.moved?"animate":"attr"]({x:r+d.x+({left:e,right:-e}[h[6]]||0),y:s+d.y});g.moved=!0;if(l&&f)g=b.connector,h=i?[oa,r+("left"===h[6]?5:-5),s,"C",r,s,2*h[2]-h[4],2*h[3]-h[5],h[2],h[3],ba,h[4],h[5]]:[oa,r+("left"===h[6]?5:-5),s,ba,h[2],h[3],ba,h[4],h[5]],g?(g.animate({d:h}),
g.attr("visibility",w)):b.connector=g=this.chart.renderer.path(h).attr({"stroke-width":f,stroke:d.connectorColor||b.color||"#606060",visibility:w,zIndex:3}).translate(c.plotLeft,c.plotTop).add()}}}},drawTracker:Ja.prototype.drawTracker,getSymbol:function(){}});ga.pie=Xc;F(Highcharts,{Chart:Vb,dateFormat:Zb,pathAnim:$a,getOptions:function(){return Oa},hasRtlBug:Pc,numberFormat:cc,Point:Ia,Color:Ha,Renderer:ac,seriesTypes:ga,setOptions:function(a){Oa=D(Oa,a);Jb();return Oa},Series:N,addEvent:ca,removeEvent:Ba,
createElement:aa,discardElement:vb,css:y,each:o,extend:F,map:ua,merge:D,pick:p,splat:sb,extendClass:V,product:"Highcharts",version:"2.1.9"})})();
